# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ganbatte < Formula
  desc "Workflow/shortcut management CLI for lazy developers"
  homepage "https://github.com/bssm-oss/ganbatte"
  version "1.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.4.2/ganbatte_darwin_amd64.tar.gz"
      sha256 "18dfef2e62f8bb2f86410aa8b5da67139d5ffccc0a58ffe3ff9eceff36b7fa16"

      define_method(:install) do
        bin.install "gnb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.4.2/ganbatte_darwin_arm64.tar.gz"
      sha256 "82cc16c18fa8d21e738dff7c02a2a4fc6e9411649557241813ca236eafcc8d08"

      define_method(:install) do
        bin.install "gnb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.4.2/ganbatte_linux_amd64.tar.gz"
      sha256 "1303ed0197dd7171d482aa995bea390955129e600c845ddd8a1799e867a1d344"
      define_method(:install) do
        bin.install "gnb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.4.2/ganbatte_linux_arm64.tar.gz"
      sha256 "419766069eba5c4475e244b8c29a97c9343dc4cca7e6721e749ffed96d246c4e"
      define_method(:install) do
        bin.install "gnb"
      end
    end
  end

  test do
    system "#{bin}/gnb", "--help"
  end
end
