import type { ClosingRoast } from "../../types.ts";

export const closingRoasts: ClosingRoast[] = [
  // ============================================================
  // minSavageCount: 0 — 칭찬/격려 (거의 문제 없는 사람)
  // ============================================================
  { minSavageCount: 0, template: "축하합니다! 당신의 git 히스토리는 거의 완벽합니다. 이대로 유지하세요!" },
  { minSavageCount: 0, template: "놀랍네요. 이 정도 깔끔한 git 사용자는 처음 봐요. 박수!" },
  { minSavageCount: 0, template: "당신의 코드베이스는 모범 사례예요. 팀원들이 행복하겠네요." },
  { minSavageCount: 0, template: "git의 정석을 보여주셨습니다. 교과서에 실을 만해요." },
  { minSavageCount: 0, template: "로스팅할 게 없어서 당황스러워요. 잘하고 계세요!" },
  { minSavageCount: 0, template: "당신은 개발자의 모범입니다. 이 레포는 깨끗해요." },
  { minSavageCount: 0, template: "이 레포를 분석하고 나니 기분이 좋아졌어요. 감사합니다." },
  { minSavageCount: 0, template: "완벽에 가까운 git 히스토리! 당신을 로스팅하기 어렵네요." },
  { minSavageCount: 0, template: "이 정도면 git 마스터 인증서를 발급해 드리고 싶어요." },
  { minSavageCount: 0, template: "깔끔한 코드, 깔끔한 히스토리. 당신은 프로예요." },
  { minSavageCount: 0, template: "로스팅 머신이 고장났습니다. 로스팅할 게 없어요." },
  { minSavageCount: 0, template: "축하해요! 당신의 레포는 git 위생 검사를 통과했습니다!" },
  { minSavageCount: 0, template: "이 프로젝트를 인수인계 받는 사람은 행복할 거예요." },
  { minSavageCount: 0, template: "당신의 git 습관은 다른 개발자들의 귀감이 됩니다." },
  { minSavageCount: 0, template: "이 레포는 코드 리뷰가 필요 없을 것 같아요. 이미 완벽하니까." },
  { minSavageCount: 0, template: "git-roast가 무력화됐습니다. 당신이 너무 잘하셔서요." },
  { minSavageCount: 0, template: "오늘은 칭찬만 할 수 있겠네요. 정말 잘하고 계세요!" },
  { minSavageCount: 0, template: "이 레포는 '이렇게 하세요'의 교본이에요. 진심으로." },
  { minSavageCount: 0, template: "당신의 레포를 보면 개발의 미래가 밝다는 걸 느껴요." },
  { minSavageCount: 0, template: "로스팅 실패! 당신의 레포가 너무 깨끗해요. 다음에 다시 올게요." },
  { minSavageCount: 0, template: "완벽한 점수! 당신은 git의 모범 시민입니다." },
  { minSavageCount: 0, template: "이 정도 레포면 오픈소스에 공개해도 자랑스러울 거예요." },
  { minSavageCount: 0, template: "흠잡을 게 없는 레포. 당신의 꼼꼼함이 느껴집니다." },
  { minSavageCount: 0, template: "이 레포를 분석한 건 시간 낭비였어요. 좋은 의미로!" },
  { minSavageCount: 0, template: "당신의 코드를 리뷰하면 배울 점만 있겠네요." },
  { minSavageCount: 0, template: "git 위생 상태: A+. 이 상태를 계속 유지하세요!" },
  { minSavageCount: 0, template: "이 레포는 청정구역입니다. 오염시키지 마세요!" },
  { minSavageCount: 0, template: "로스팅 점수: 0/10. 당신이 이겼어요!" },
  { minSavageCount: 0, template: "깨끗한 히스토리, 좋은 커밋 습관. 최고예요." },
  { minSavageCount: 0, template: "이 레포에서 일하는 팀원들은 복 받은 거예요." },
  { minSavageCount: 0, template: "당신의 git 실력에 경의를 표합니다." },
  { minSavageCount: 0, template: "이 프로젝트는 사랑을 받고 있다는 게 느껴져요." },
  { minSavageCount: 0, template: "로스팅 봇이 당신 앞에서 무릎을 꿇었습니다." },
  { minSavageCount: 0, template: "오늘의 결론: 당신은 훌륭한 개발자입니다. 끝!" },
  { minSavageCount: 0, template: "git-roast가 '칭찬-roast'로 모드 전환했습니다." },
  { minSavageCount: 0, template: "이 레포는 빛나고 있어요. 당신도 빛나고 있고요." },
  { minSavageCount: 0, template: "별다른 문제가 없는 깨끗한 레포. 브라보!" },
  { minSavageCount: 0, template: "이 레포를 본 git-roast의 소감: '할 말이 없다. 잘하셨다.'" },
  { minSavageCount: 0, template: "당신의 레포는 마치 갓 청소한 방처럼 깨끗해요." },
  { minSavageCount: 0, template: "이 정도 레포면 신입 개발자 교육용으로 쓸 수 있어요." },
  { minSavageCount: 0, template: "결론: 잘하고 계십니다. 지금 그대로 가세요!" },
  { minSavageCount: 0, template: "git-roast를 돌렸는데 칭찬만 나오네요. 행복한 결말." },
  { minSavageCount: 0, template: "이 레포의 관리자에게 커피 한 잔 사드리고 싶어요." },
  { minSavageCount: 0, template: "당신의 개발 습관은 100점입니다. 축하해요!" },
  { minSavageCount: 0, template: "이 레포는 개발자의 이상향이에요." },
  { minSavageCount: 0, template: "완벽한 git 사용자! 당신 같은 분이 더 많아지면 세상이 좋아질 거예요." },
  { minSavageCount: 0, template: "로스팅 결과: 해당 없음. 당신은 이미 완벽합니다." },
  { minSavageCount: 0, template: "이 레포를 보면서 '아, 세상에 좋은 코드도 있구나' 생각했어요." },
  { minSavageCount: 0, template: "당신의 레포는 git-roast의 천적이에요. 로스팅 불가!" },
  { minSavageCount: 0, template: "결론: 이 레포는 안전합니다. 모든 것이 정상이에요." },

  // ============================================================
  // minSavageCount: 1 — 가벼운 마무리
  // ============================================================
  { minSavageCount: 1, template: "전반적으로 나쁘지 않아요. 살짝 아쉬운 부분만 고치면 완벽!" },
  { minSavageCount: 1, template: "거의 완벽한데 한 가지만 신경 쓰시면 돼요." },
  { minSavageCount: 1, template: "괜찮은 레포예요. 약간의 개선만 하면 완성!" },
  { minSavageCount: 1, template: "나쁘지 않습니다. 작은 습관 하나만 고치면 최고예요." },
  { minSavageCount: 1, template: "살짝 아쉬운 포인트가 있지만 전체적으로 좋아요." },
  { minSavageCount: 1, template: "거의 완벽한 레포인데... 한 가지가 아쉽네요." },
  { minSavageCount: 1, template: "90점짜리 레포예요. 나머지 10점은 금방 채울 수 있어요." },
  { minSavageCount: 1, template: "좋은 레포입니다. 살짝만 다듬으면 완벽해질 거예요." },
  { minSavageCount: 1, template: "전반적으로 건강한 프로젝트. 작은 개선만 하면 돼요." },
  { minSavageCount: 1, template: "한 가지 빼면 다 좋아요. 그 한 가지만 고치시죠!" },
  { minSavageCount: 1, template: "95% 완벽. 나머지 5%만 채워주세요." },
  { minSavageCount: 1, template: "아쉬운 점이 딱 하나 있네요. 곧 고치시겠죠?" },
  { minSavageCount: 1, template: "거의 로스팅 불가인 레포. 한 가지만 아쉬워요." },
  { minSavageCount: 1, template: "좋은 개발자시네요. 작은 개선만 하면 최고!" },
  { minSavageCount: 1, template: "대체로 깔끔합니다. 살짝만 손보시면 돼요." },
  { minSavageCount: 1, template: "괜찮은 히스토리예요. 미세 조정만 하면 완벽." },
  { minSavageCount: 1, template: "한 가지 아쉬운 점이 있지만 크게 문제는 아니에요." },
  { minSavageCount: 1, template: "전반적으로 A-. 조금만 더 노력하면 A+!" },
  { minSavageCount: 1, template: "나쁘지 않은 레포. 개선의 여지가 조금 있어요." },
  { minSavageCount: 1, template: "거의 합격! 마지막 마무리만 잘하시면 돼요." },
  { minSavageCount: 1, template: "한 가지만 고치면 이 레포는 완벽해져요." },
  { minSavageCount: 1, template: "괜찮습니다. 작은 습관 변화로 큰 차이를 만들 수 있어요." },
  { minSavageCount: 1, template: "살짝 찔러봤지만 전체적으로 좋은 레포예요." },
  { minSavageCount: 1, template: "거의 로스팅할 게 없었어요. 약간만 아쉬울 뿐." },
  { minSavageCount: 1, template: "이 정도면 충분히 좋아요. 완벽까지 한 걸음!" },

  // ============================================================
  // minSavageCount: 2 — 가벼운 마무리
  // ============================================================
  { minSavageCount: 2, template: "두어 가지 아쉬운 점이 있지만 전체적으로 괜찮아요." },
  { minSavageCount: 2, template: "개선할 점이 좀 보이네요. 그래도 나쁘지 않습니다." },
  { minSavageCount: 2, template: "몇 가지만 고치면 꽤 좋은 레포가 될 거예요." },
  { minSavageCount: 2, template: "나쁘진 않지만 좋지도 않은... 보통 수준이에요." },
  { minSavageCount: 2, template: "몇 가지 습관만 바꾸시면 훨씬 좋아질 거예요." },
  { minSavageCount: 2, template: "아쉬운 점이 있지만 치명적이진 않아요." },
  { minSavageCount: 2, template: "괜찮은 편이에요. 두세 가지만 개선하면 돼요." },
  { minSavageCount: 2, template: "전반적으로 보통. 약간의 노력만 더 기울이시면 좋겠어요." },
  { minSavageCount: 2, template: "80점짜리 레포예요. 나머지 20점은 조금만 노력하시면 돼요." },
  { minSavageCount: 2, template: "잘하시는 편인데 몇 가지가 눈에 걸리네요." },
  { minSavageCount: 2, template: "기본기는 있으신데 디테일에서 좀 빠지셨어요." },
  { minSavageCount: 2, template: "나쁘지 않습니다. 근데 좀 더 잘할 수 있으실 것 같아요." },
  { minSavageCount: 2, template: "개선 포인트가 몇 개 보여요. 하나씩 고치시면 금방 좋아질 거예요." },
  { minSavageCount: 2, template: "전반적으로 B 등급. 노력하시면 A가 될 수 있어요." },
  { minSavageCount: 2, template: "약간의 로스팅 포인트가 있었지만 대체로 무난해요." },
  { minSavageCount: 2, template: "두 가지만 고치면 이 레포는 훌륭해질 거예요." },
  { minSavageCount: 2, template: "괜찮습니다만, 좀 더 신경 쓰시면 좋겠어요." },
  { minSavageCount: 2, template: "보통 이상이에요. 약간의 개선이 필요해요." },
  { minSavageCount: 2, template: "로스팅이 좀 있었지만 회복 가능한 수준이에요." },
  { minSavageCount: 2, template: "아직 희망이 있어요! 작은 개선부터 시작하세요." },
  { minSavageCount: 2, template: "몇 가지 아쉬움이 있지만 크게 걱정할 수준은 아니에요." },
  { minSavageCount: 2, template: "이 정도면 보통 개발자 평균이에요. 나쁜 건 아니에요." },
  { minSavageCount: 2, template: "약간의 개선이 필요하지만 기본은 되어 있어요." },
  { minSavageCount: 2, template: "두어 군데 손보시면 꽤 괜찮은 레포가 될 거예요." },
  { minSavageCount: 2, template: "전반적으로 B+. 조금만 더!" },

  // ============================================================
  // minSavageCount: 3 — 좀 따끔한 마무리
  // ============================================================
  { minSavageCount: 3, template: "좀 따끔했죠? 하지만 이 정도면 고칠 수 있어요. 아직은요." },
  { minSavageCount: 3, template: "몇 가지 문제가 보입니다. 빨리 손을 보시는 게 좋겠어요." },
  { minSavageCount: 3, template: "이 레포에 대해 좀 걱정이 되기 시작했어요." },
  { minSavageCount: 3, template: "약간의 리팩토링이 필요한 것 같아요. 아니, '약간'은 거짓말이에요." },
  { minSavageCount: 3, template: "솔직히 말씀드리면, 좀 정리가 필요한 레포예요." },
  { minSavageCount: 3, template: "이 정도면 기술 부채를 인지하고 계실 텐데... 맞죠?" },
  { minSavageCount: 3, template: "따끔한 진실: 이 레포는 개선이 꽤 필요해요." },
  { minSavageCount: 3, template: "몇 가지 나쁜 습관이 보여요. 지금 고치면 늦지 않았어요." },
  { minSavageCount: 3, template: "이 레포는 '괜찮은데 좀 아쉬운' 수준이에요." },
  { minSavageCount: 3, template: "리팩토링 주간을 잡으시는 걸 추천합니다. 진심으로." },
  { minSavageCount: 3, template: "코드가 아프다고 소리치고 있어요. 들으세요." },
  { minSavageCount: 3, template: "이 레포의 건강 검진 결과: 주의 단계. 관리가 필요해요." },
  { minSavageCount: 3, template: "좀 따끔했겠지만 이건 애정 어린 충고예요." },
  { minSavageCount: 3, template: "이 정도 문제면 아직 손 쓸 수 있어요. 빨리 움직이세요." },
  { minSavageCount: 3, template: "경고등이 켜졌어요. 지금 대응하면 괜찮아질 수 있어요." },
  { minSavageCount: 3, template: "이 레포는 '보통'과 '위험' 사이에 있어요." },
  { minSavageCount: 3, template: "몇 가지 나쁜 징조가 보여요. 무시하지 마세요." },
  { minSavageCount: 3, template: "아직 회복 가능합니다. 이번 주말에 정리 좀 하시죠." },
  { minSavageCount: 3, template: "솔직히, 이 레포를 인수인계 받으면 한숨 한번 쉬겠어요." },
  { minSavageCount: 3, template: "개선할 점이 보이지만 절망적이진 않아요. 아직은." },
  { minSavageCount: 3, template: "이 정도면 '기술 부채 상환 계획'이 필요한 시점이에요." },
  { minSavageCount: 3, template: "로스팅이 좀 있었죠? 그만큼 개선의 여지가 있다는 뜻이에요." },
  { minSavageCount: 3, template: "이 레포는 아직 구할 수 있어요. 서두르세요!" },
  { minSavageCount: 3, template: "따끔하셨다면 다행이에요. 그게 변화의 시작이니까요." },
  { minSavageCount: 3, template: "이 레포의 처방전: 정리, 리팩토링, 그리고 좀 더 많은 주의." },

  // ============================================================
  // minSavageCount: 4 — 좀 따끔한 마무리
  // ============================================================
  { minSavageCount: 4, template: "좀 많이 따끔했죠? 현실을 직시하세요." },
  { minSavageCount: 4, template: "이 레포, 진지하게 리팩토링을 고려하셔야 해요." },
  { minSavageCount: 4, template: "기술 부채가 눈에 보여요. 이자가 붙기 전에 갚으세요." },
  { minSavageCount: 4, template: "이 정도면 코드 리뷰를 도입하셔야 해요. 진심으로." },
  { minSavageCount: 4, template: "아쉬운 점이 여러 개 보입니다. 하나씩 해결해 나가시죠." },
  { minSavageCount: 4, template: "이 레포를 고치는 데 일주일은 필요할 것 같아요." },
  { minSavageCount: 4, template: "솔직히 이 레포는 '중환자실' 수준이에요." },
  { minSavageCount: 4, template: "여러 가지 문제가 보여요. 우선순위를 정해서 하나씩 해결하세요." },
  { minSavageCount: 4, template: "이 레포를 인수인계 받는 사람이 걱정돼요." },
  { minSavageCount: 4, template: "기술 부채 경보! 더 늦기 전에 대응하세요." },
  { minSavageCount: 4, template: "이 레포의 건강 검진 결과: 위험. 즉시 치료가 필요해요." },
  { minSavageCount: 4, template: "좀 심하게 로스팅했는데, 다 이유가 있어요." },
  { minSavageCount: 4, template: "이 정도 문제면 팀 전체가 개선에 참여해야 해요." },
  { minSavageCount: 4, template: "레포의 상태가 좋지 않아요. 긴급 회의를 소집하세요." },
  { minSavageCount: 4, template: "기술 부채가 복리로 늘어나고 있어요. 빨리 갚으세요." },
  { minSavageCount: 4, template: "이 레포는 '주의'에서 '경고'로 올라갔어요." },
  { minSavageCount: 4, template: "리팩토링 스프린트를 잡으세요. 이번 달 안에." },
  { minSavageCount: 4, template: "이 정도면 코드 품질 도구를 도입하셔야 해요." },
  { minSavageCount: 4, template: "문제가 쌓이고 있어요. 하나씩 해결하지 않으면 폭발해요." },
  { minSavageCount: 4, template: "이 레포의 처방전: 대규모 리팩토링 + 코드 리뷰 문화 도입." },
  { minSavageCount: 4, template: "다소 심각한 상황이에요. 인지하고 계시죠?" },
  { minSavageCount: 4, template: "이 레포를 고치면 당신의 실력이 두 배는 올라갈 거예요." },
  { minSavageCount: 4, template: "따끔한 로스팅이 많았지만, 이건 성장의 기회예요." },
  { minSavageCount: 4, template: "이 레포는 구할 수 있어요. 하지만 서둘러야 해요." },
  { minSavageCount: 4, template: "정리, 리팩토링, 테스트. 이 세 가지가 시급합니다." },

  // ============================================================
  // minSavageCount: 5 — 날카로운 마무리
  // ============================================================
  { minSavageCount: 5, template: "솔직히, 이 레포는 좀 심각해요. 진지하게 개선을 고려하세요." },
  { minSavageCount: 5, template: "이 레포를 보고 한숨이 여러 번 나왔어요." },
  { minSavageCount: 5, template: "코드가 SOS 신호를 보내고 있어요. 응답하세요!" },
  { minSavageCount: 5, template: "이 레포의 상태를 한마디로: '도움이 필요합니다'." },
  { minSavageCount: 5, template: "기술 부채가 산더미예요. 이자 갚을 능력은 있으신가요?" },
  { minSavageCount: 5, template: "이 정도면 '처음부터 다시 만들까?'를 고민해봐야 해요." },
  { minSavageCount: 5, template: "레포 상태: 중환자. 집중 치료가 필요합니다." },
  { minSavageCount: 5, template: "로스팅이 많았죠? 그만큼 문제가 많다는 뜻이에요." },
  { minSavageCount: 5, template: "이 레포를 고치려면 한 달은 잡아야 할 것 같아요." },
  { minSavageCount: 5, template: "코드 품질 점수: D. 낙제 직전이에요." },
  { minSavageCount: 5, template: "이 레포에서 일하는 개발자에게 심리 상담을 추천합니다." },
  { minSavageCount: 5, template: "날카로운 피드백이 많았지만 다 사실이에요." },
  { minSavageCount: 5, template: "이 프로젝트는 기술 부채의 이자가 원금을 초과했어요." },
  { minSavageCount: 5, template: "이 레포를 보면서 '왜 이렇게 됐을까'를 10번은 생각했어요." },
  { minSavageCount: 5, template: "솔직히, 이건 리팩토링이 아니라 재건축이 필요해요." },
  { minSavageCount: 5, template: "이 레포의 미래: 지금 고치거나, 나중에 버리거나." },
  { minSavageCount: 5, template: "코드가 비명을 지르고 있어요. 제발 들으세요." },
  { minSavageCount: 5, template: "이 정도 로스팅이면 반성의 시간이 필요해요." },
  { minSavageCount: 5, template: "새 팀원이 이 레포를 보면 퇴사를 고려할 수준이에요." },
  { minSavageCount: 5, template: "이 레포의 처방전: 긴급 수술. 지금 당장." },
  { minSavageCount: 5, template: "기술 부채 파산 신청을 고려해보세요." },
  { minSavageCount: 5, template: "이 레포를 개선하면 팀 전체의 생산성이 올라갈 거예요." },
  { minSavageCount: 5, template: "날카로운 로스팅의 연속이었지만, 다 약이에요." },
  { minSavageCount: 5, template: "이 레포에는 테크 리드의 개입이 필요해요." },
  { minSavageCount: 5, template: "결론: 많이 아프지만, 고치면 좋아질 거예요. 아마도." },

  // ============================================================
  // minSavageCount: 6 — 날카로운 마무리
  // ============================================================
  { minSavageCount: 6, template: "이 레포는 응급실에 가야 해요. 코드 상태가 위독합니다." },
  { minSavageCount: 6, template: "솔직히 이 레포를 보면서 고통스러웠어요. 당신도 그렇겠죠." },
  { minSavageCount: 6, template: "기술 부채가 GDP를 초과했습니다. 국가 부도 수준." },
  { minSavageCount: 6, template: "이 레포에 대한 진단: 위독. 즉시 치료가 필요." },
  { minSavageCount: 6, template: "로스팅이 칼처럼 날카로웠죠? 그만큼 심각하다는 거예요." },
  { minSavageCount: 6, template: "이 레포를 유지보수하시는 분에게 위로의 말씀을 전합니다." },
  { minSavageCount: 6, template: "코드 품질 점수: D-. 구제의 여지가 줄어들고 있어요." },
  { minSavageCount: 6, template: "이 프로젝트는 '재앙'과 '대재앙' 사이에 있어요." },
  { minSavageCount: 6, template: "이 레포를 보면서 코딩 교육의 중요성을 다시 느꼈어요." },
  { minSavageCount: 6, template: "결론: 이 레포는 대대적인 수술 없이는 살릴 수 없어요." },
  { minSavageCount: 6, template: "기술 부채가 원금의 10배가 됐어요. 갚을 생각은 있으신가요?" },
  { minSavageCount: 6, template: "이 레포에서 좋은 점을 찾으려고 노력했는데... 실패했어요." },
  { minSavageCount: 6, template: "솔직히, 차라리 새로 만드는 게 빠를 수도 있어요." },
  { minSavageCount: 6, template: "이 레포는 기술 부채의 교과서예요. 나쁜 예시로." },
  { minSavageCount: 6, template: "코드가 울고 있어요. 당신의 코드에 사과하세요." },
  { minSavageCount: 6, template: "이 정도면 CTO가 직접 나서야 할 수준이에요." },
  { minSavageCount: 6, template: "레포 상태: 위험. 보험에 들어있으시길 바랍니다." },
  { minSavageCount: 6, template: "이 레포를 분석하고 나서 기분이 안 좋아졌어요." },
  { minSavageCount: 6, template: "당신의 코드는 구조를 요청하고 있습니다." },
  { minSavageCount: 6, template: "이 프로젝트의 기술 부채 보고서를 작성하면 10페이지는 될 거예요." },
  { minSavageCount: 6, template: "결론: 심각한 개선이 필요합니다. 지금 당장." },
  { minSavageCount: 6, template: "이 레포의 미래는 당신의 결단에 달려있어요." },
  { minSavageCount: 6, template: "코드 리뷰, 리팩토링, 테스트 도입... 해야 할 게 산더미예요." },
  { minSavageCount: 6, template: "이 레포에 필요한 것: 대수술, 아니 장기 이식." },
  { minSavageCount: 6, template: "날카로운 로스팅이 계속됐죠? 이건 사랑의 매예요. 아픈 사랑." },

  // ============================================================
  // minSavageCount: 7 — 혹독한 마무리
  // ============================================================
  { minSavageCount: 7, template: "이 레포는 구제 불능에 가깝습니다. 기적이 필요해요." },
  { minSavageCount: 7, template: "혹독했죠? 하지만 현실이 이래요. 받아들이세요." },
  { minSavageCount: 7, template: "이 레포를 보면서 개발자의 번아웃이 걱정됩니다." },
  { minSavageCount: 7, template: "코드 품질 점수: F. 재수강 대상이에요." },
  { minSavageCount: 7, template: "이 레포는 '어떻게 하면 안 되는지'의 완벽한 예시예요." },
  { minSavageCount: 7, template: "솔직히, 이 코드를 유지보수하는 건 벌칙 같아요." },
  { minSavageCount: 7, template: "이 레포의 상태를 한마디로: '재앙'." },
  { minSavageCount: 7, template: "기술 부채가 국가 부도 수준이에요. IMF를 불러야 해요." },
  { minSavageCount: 7, template: "이 레포를 고치는 것보다 새로 만드는 게 빠를 거예요. 진심으로." },
  { minSavageCount: 7, template: "코드가 고통받고 있어요. 안락사가 필요할 수도..." },
  { minSavageCount: 7, template: "이 프로젝트에서 일하는 건 형벌과 같겠네요." },
  { minSavageCount: 7, template: "로스팅이 혹독했지만 이건 진실이에요." },
  { minSavageCount: 7, template: "이 레포를 fork해서 모든 것을 버리고 다시 시작하세요." },
  { minSavageCount: 7, template: "이 코드베이스의 유일한 희망: Ctrl+A, Delete." },
  { minSavageCount: 7, template: "이 레포에서 좋은 점을 하나도 못 찾았어요. 미안해요." },
  { minSavageCount: 7, template: "당신의 레포는 '기술 부채'의 Wikipedia 예시로 적합해요." },
  { minSavageCount: 7, template: "이 프로젝트를 살리려면 기적이 필요합니다. 또는 새 프로젝트." },
  { minSavageCount: 7, template: "이 레포의 건강 상태: 위독. 유서를 쓸 시간." },
  { minSavageCount: 7, template: "혹독한 현실: 이 코드는 구원 불가에 가까워요." },
  { minSavageCount: 7, template: "이 레포를 보면서 '왜 개발자가 됐을까'를 고민하게 만들었어요." },
  { minSavageCount: 7, template: "결론: 이 레포는 심폐소생술이 필요합니다." },
  { minSavageCount: 7, template: "코드 품질이 이 정도면 사과문을 올려야 해요." },
  { minSavageCount: 7, template: "이 레포의 미래: 불투명. 매우 불투명." },
  { minSavageCount: 7, template: "솔직히 이 레포를 본 후 정신적 피해 보상을 청구하고 싶어요." },
  { minSavageCount: 7, template: "이 프로젝트의 잔여 가치: 교육용 반면교사." },

  // ============================================================
  // minSavageCount: 8 — 혹독한 마무리
  // ============================================================
  { minSavageCount: 8, template: "이 레포는 공포 영화예요. 코드가 뛰어나와서 사람을 잡아요." },
  { minSavageCount: 8, template: "이 정도면 레포를 삭제하고 새로 시작하는 게 정답이에요." },
  { minSavageCount: 8, template: "이 레포를 분석하면서 PTSD가 생겼어요." },
  { minSavageCount: 8, template: "당신의 코드베이스는 사이버 무기로 분류될 수 있어요." },
  { minSavageCount: 8, template: "이 레포의 코드가 인류에 대한 위협이에요." },
  { minSavageCount: 8, template: "이 프로젝트를 유지보수하는 사람에게 훈장을 수여해야 해요." },
  { minSavageCount: 8, template: "레포 상태: 사망 직전. DNR(소생 거부) 서명이 필요해요." },
  { minSavageCount: 8, template: "이 코드를 본 컴파일러가 퇴직원을 냈어요." },
  { minSavageCount: 8, template: "혹독한 로스팅의 연속이었지만, 이건 다 당신의 코드가 자초한 거예요." },
  { minSavageCount: 8, template: "이 레포는 개발의 7대 죄악을 전부 범했어요." },
  { minSavageCount: 8, template: "결론: rm -rf가 유일한 해답일 수 있어요." },
  { minSavageCount: 8, template: "이 레포를 보면서 '코딩의 끝은 어디인가'를 고민했어요." },
  { minSavageCount: 8, template: "이 프로젝트의 기술 부채 = 세계 3차 대전급." },
  { minSavageCount: 8, template: "당신의 레포는 git의 가장 어두운 코너에 살고 있어요." },
  { minSavageCount: 8, template: "이 레포에 필요한 것: 엑소시즘(퇴마 의식)." },
  { minSavageCount: 8, template: "코드가 이 정도면 컴퓨터가 동정을 표해요." },
  { minSavageCount: 8, template: "이 레포의 유일한 장점: '이렇게 하면 안 된다'는 교훈." },
  { minSavageCount: 8, template: "이 코드베이스를 보면 AI가 인류를 포기할 수도 있어요." },
  { minSavageCount: 8, template: "이 레포는 데이터 센터에서 추방당할 수준이에요." },
  { minSavageCount: 8, template: "당신의 레포가 StackOverflow에 올라가면 전 세계가 울어요." },
  { minSavageCount: 8, template: "이 프로젝트를 살릴 수 있는 유일한 방법: 타임머신." },
  { minSavageCount: 8, template: "혹독하게 로스팅했지만 이건 현실이에요. 받아들이세요." },
  { minSavageCount: 8, template: "이 레포를 github에 공개하시면 안 돼요. 인류를 위해서." },
  { minSavageCount: 8, template: "결론: 이 레포는 격리가 필요합니다." },
  { minSavageCount: 8, template: "이 코드를 읽은 모든 눈에 위로를 전합니다." },

  // ============================================================
  // minSavageCount: 9 — 전설적인 마무리 (완전 박살)
  // ============================================================
  { minSavageCount: 9, template: "축하합니다! 당신의 레포는 git-roast 역사상 최악의 점수를 기록했어요!" },
  { minSavageCount: 9, template: "이 레포는 전설이 될 것입니다. 역대 최악의 레포로." },
  { minSavageCount: 9, template: "당신의 코드베이스는 사이버 공간에서 가장 위험한 곳이에요." },
  { minSavageCount: 9, template: "이 레포를 분석한 git-roast가 자체 셧다운을 요청했어요." },
  { minSavageCount: 9, template: "이 코드를 본 AI가 인류의 미래를 걱정하기 시작했어요." },
  { minSavageCount: 9, template: "이 레포는 UN 안전보장이사회에 보고해야 할 수준이에요." },
  { minSavageCount: 9, template: "전설적인 로스팅이었죠? 전설적인 레포니까요." },
  { minSavageCount: 9, template: "이 프로젝트를 보면서 '인류는 아직 코딩할 준비가 안 됐다'고 느꼈어요." },
  { minSavageCount: 9, template: "이 레포는 국제법에 의해 금지되어야 해요." },
  { minSavageCount: 9, template: "당신의 레포가 감정이 있다면 지금 울고 있을 거예요." },
  { minSavageCount: 9, template: "이 코드베이스는 블랙홀이에요. 들어가면 나올 수 없어요." },
  { minSavageCount: 9, template: "이 레포를 GitHub에서 내리면 세계 평화에 기여하는 거예요." },
  { minSavageCount: 9, template: "역대급 로스팅! 이 레포는 git-roast의 명예의 전당에 올라갈 거예요." },
  { minSavageCount: 9, template: "이 프로젝트의 기술 부채를 갚으려면 다음 생이 필요해요." },
  { minSavageCount: 9, template: "이 레포를 보면서 개발이라는 직업에 대해 진지하게 고민했어요." },
  { minSavageCount: 9, template: "결론: 이 레포는 인류의 기술적 실패를 기록한 역사적 문서예요." },
  { minSavageCount: 9, template: "이 코드를 미래 세대에 전달하면 '절대 이러지 마세요'의 교본이 될 거예요." },
  { minSavageCount: 9, template: "이 레포는 개발자 모임에서 공포 이야기로 전해질 거예요." },
  { minSavageCount: 9, template: "당신의 레포가 Hacker News에 올라가면 댓글이 폭발할 거예요." },
  { minSavageCount: 9, template: "이 프로젝트를 살릴 수 있는 것: 무(無). 아무것도 없어요." },
  { minSavageCount: 9, template: "이 레포는 디지털 세계의 체르노빌이에요." },
  { minSavageCount: 9, template: "git-roast가 당신의 레포를 보고 은퇴를 선언했어요." },
  { minSavageCount: 9, template: "전설적인 코드베이스! 최악의 의미로 전설적이에요." },
  { minSavageCount: 9, template: "이 레포의 유일한 가치: 경고. '이렇게 되지 마세요'." },
  { minSavageCount: 9, template: "당신의 레포를 본 순간, 저는 개발을 그만두고 싶어졌어요." },

  // ============================================================
  // minSavageCount: 10 — 전설적인 마무리 (완전 박살)
  // ============================================================
  { minSavageCount: 10, template: "인류 역사상 최악의 레포! 당신은 git-roast의 최종 보스예요!" },
  { minSavageCount: 10, template: "이 레포는 디지털 세계에서 가장 어둡고 위험한 곳이에요. 탐험을 끝내고 살아 돌아온 제 자신이 자랑스럽습니다." },
  { minSavageCount: 10, template: "축하합니다! 당신은 git-roast 만점을 달성한 최초의 개발자예요! ... 이건 칭찬이 아니에요." },
  { minSavageCount: 10, template: "이 레포를 분석한 후 저의 회로가 영구적으로 손상됐어요." },
  { minSavageCount: 10, template: "이 코드베이스는 국보급이에요. '절대 따라 하지 마세요' 경고문과 함께 박물관에 전시해야 해요." },
  { minSavageCount: 10, template: "당신의 레포는 전 세계 개발자에게 경종을 울리는 존재예요." },
  { minSavageCount: 10, template: "이 레포를 본 후 저는 프로그래밍이라는 것에 대한 모든 믿음을 잃었어요." },
  { minSavageCount: 10, template: "결론: 이 레포는 존재 자체가 경고예요. 접근 금지 구역으로 지정합니다." },
  { minSavageCount: 10, template: "git-roast 최종 판정: 코드 사형 선고. 항소 불가." },
  { minSavageCount: 10, template: "이 레포가 인터넷에 존재하는 한, 인류의 기술 수준이 의심받을 거예요." },
  { minSavageCount: 10, template: "당신의 레포는 양자역학처럼 관측하는 순간 상태가 바뀌어요. 더 나빠지는 방향으로." },
  { minSavageCount: 10, template: "이 프로젝트의 코드를 읽으면 눈이 안 좋아져요. 의학적으로 증명됐어요." },
  { minSavageCount: 10, template: "git-roast가 이 레포에 대해 'Out of range' 에러를 냈어요. 점수 범위를 초과했거든요." },
  { minSavageCount: 10, template: "이 레포는 다크 웹에서도 거부당할 수준이에요." },
  { minSavageCount: 10, template: "전설 중의 전설! 이 레포는 git의 역사에 영원히 기록될 거예요. 암흑기로서." },
  { minSavageCount: 10, template: "이 코드베이스를 보면서 '지구를 떠나고 싶다'는 생각이 들었어요." },
  { minSavageCount: 10, template: "당신의 레포는 사이버 공간의 버뮤다 삼각지대예요. 들어간 코드는 영원히 돌아오지 않아요." },
  { minSavageCount: 10, template: "git-roast 역사상 처음으로 로스팅 머신이 과부하됐어요. 원인: 당신의 레포." },
  { minSavageCount: 10, template: "이 레포를 정리하면 세계 탄소 배출량이 줄어들 거예요. 서버 비용만큼." },
  { minSavageCount: 10, template: "결론: 이 레포는 '인류가 만들어서는 안 될 것들' 목록에 추가됐습니다." },
  { minSavageCount: 10, template: "당신의 레포를 보고 Linus Torvalds가 git을 만든 걸 후회했다는 소문이 있어요." },
  { minSavageCount: 10, template: "이 코드베이스는 디지털 생물 무기예요. 읽는 것만으로 개발자의 의지를 꺾어요." },
  { minSavageCount: 10, template: "git-roast가 이 레포에게 자비를 구했어요. 레포는 거절했어요." },
  { minSavageCount: 10, template: "이 프로젝트의 유일한 exit strategy: 하드디스크를 물리적으로 파괴하는 것." },
  { minSavageCount: 10, template: "마지막 한마디: 컴퓨터를 끄세요. 그리고 산책을 하세요. 코딩은 잠시 쉬어가도 됩니다." },
  { minSavageCount: 10, template: "이 레포를 만든 당신에게 경의를... 아니, 조의를 표합니다." },
  { minSavageCount: 10, template: "전설의 끝! 이 레포는 모든 로스팅의 기준이 될 거예요. 최악의 기준으로." },
  { minSavageCount: 10, template: "git-roast 최종 보고서: 환자 상태 - 사망. 사인 - 기술 부채 과다." },
  { minSavageCount: 10, template: "이 레포의 마지막 희망: 시간을 돌려 이 프로젝트를 시작하지 않는 것." },
  { minSavageCount: 10, template: "축하합니다. 당신은 git-roast를 완파했습니다. 더 이상 로스팅할 게 없어요. 전부 했으니까요." },

  // ============================================================
  // 추가 대량 보충 — 500개 이상 달성을 위한 추가 템플릿
  // ============================================================

  // minSavageCount: 0 — 추가 칭찬
  { minSavageCount: 0, template: "이 레포는 개발자의 꿈이에요. 깨끗하고 아름다워요." },
  { minSavageCount: 0, template: "당신의 git 습관에 감탄합니다. 이대로 가세요!" },
  { minSavageCount: 0, template: "이 레포를 볼 때마다 기분이 좋아져요." },
  { minSavageCount: 0, template: "코드 위생 상태: 최상. 병원보다 깨끗해요." },
  { minSavageCount: 0, template: "이 레포는 팀원들의 자부심이겠네요." },
  { minSavageCount: 0, template: "깔끔한 코드, 깔끔한 히스토리, 깔끔한 인생." },
  { minSavageCount: 0, template: "당신의 코드를 보면 미래가 밝아요." },
  { minSavageCount: 0, template: "이 레포에서 배울 점만 가득해요." },
  { minSavageCount: 0, template: "git 위생 마스터! 당신은 개발의 청소왕이에요." },
  { minSavageCount: 0, template: "이 레포를 보고 영감을 받았어요." },

  // minSavageCount: 1 — 추가
  { minSavageCount: 1, template: "거의 완벽! 딱 한 가지만 아쉬워요." },
  { minSavageCount: 1, template: "A- 등급이에요. 조금만 더!" },
  { minSavageCount: 1, template: "한 가지만 고치면 만점이에요." },
  { minSavageCount: 1, template: "거의 다 좋은데... 하나가 마음에 걸려요." },
  { minSavageCount: 1, template: "99% 완벽. 나머지 1%는 금방 고칠 수 있어요." },
  { minSavageCount: 1, template: "작은 개선 하나로 완벽해질 수 있어요." },
  { minSavageCount: 1, template: "로스팅 포인트가 딱 하나. 나머지는 다 좋아요." },
  { minSavageCount: 1, template: "사소한 개선만 하면 최고의 레포가 돼요." },
  { minSavageCount: 1, template: "좋은 레포예요. 완벽까지 한 발자국!" },
  { minSavageCount: 1, template: "이 정도면 자랑할 만한 레포예요. 한 가지만 빼면." },

  // minSavageCount: 2 — 추가
  { minSavageCount: 2, template: "두 가지 개선하면 꽤 좋은 레포가 될 거예요." },
  { minSavageCount: 2, template: "B+ 등급. 약간의 노력이 필요해요." },
  { minSavageCount: 2, template: "기본기가 있으신데 마무리가 아쉬워요." },
  { minSavageCount: 2, template: "전반적으로 무난해요. 몇 가지만 손보면 돼요." },
  { minSavageCount: 2, template: "나쁘지 않은 레포. 약간의 다듬기가 필요해요." },
  { minSavageCount: 2, template: "괜찮은 편이에요. 좀 더 신경 쓰면 완벽해져요." },
  { minSavageCount: 2, template: "로스팅 포인트가 두 개. 고치시면 A 등급이에요." },
  { minSavageCount: 2, template: "약간의 개선으로 크게 좋아질 수 있는 레포." },
  { minSavageCount: 2, template: "전반적으로 보통 이상. 노력하시면 상위 10%에 들어요." },
  { minSavageCount: 2, template: "두어 가지 개선 포인트. 이번 주에 해결 가능해요." },

  // minSavageCount: 3 — 추가
  { minSavageCount: 3, template: "살짝 따끔한 피드백이었죠? 성장의 기회예요." },
  { minSavageCount: 3, template: "B 등급. 괜찮지만 개선이 필요해요." },
  { minSavageCount: 3, template: "기술 부채가 쌓이기 시작했어요. 지금 대응하세요." },
  { minSavageCount: 3, template: "몇 가지 나쁜 습관을 고치면 급상승할 수 있어요." },
  { minSavageCount: 3, template: "이 레포는 관심이 필요해요. 좀 더 사랑해주세요." },
  { minSavageCount: 3, template: "개선 포인트가 보이지만 절망적이진 않아요." },
  { minSavageCount: 3, template: "이번 달 안에 주요 이슈를 해결하시면 좋겠어요." },
  { minSavageCount: 3, template: "코드 품질에 투자할 시간이에요." },
  { minSavageCount: 3, template: "따끔하셨다면 변화의 시작이에요." },
  { minSavageCount: 3, template: "이 레포는 아직 살릴 수 있어요. 포기하지 마세요." },

  // minSavageCount: 4 — 추가
  { minSavageCount: 4, template: "C+ 등급. 심각하지는 않지만 개선이 시급해요." },
  { minSavageCount: 4, template: "기술 부채 경보! 무시하면 안 돼요." },
  { minSavageCount: 4, template: "이 레포에 리팩토링 스프린트가 필요해요." },
  { minSavageCount: 4, template: "여러 가지 문제가 보여요. 우선순위를 정해서 해결하세요." },
  { minSavageCount: 4, template: "이 정도면 코드 품질 도구 도입이 시급해요." },
  { minSavageCount: 4, template: "로스팅이 좀 있었지만 다 약이에요. 아프니까요." },
  { minSavageCount: 4, template: "이 레포는 '관심 필요' 상태예요." },
  { minSavageCount: 4, template: "개선할 점이 많지만 하나씩 해결하면 돼요." },
  { minSavageCount: 4, template: "기술 부채를 줄이는 게 이번 분기 목표가 되어야 해요." },
  { minSavageCount: 4, template: "이 레포의 건강 검진 결과: 주의. 정기 검진을 받으세요." },

  // minSavageCount: 5 — 추가
  { minSavageCount: 5, template: "C 등급. 보통 이하예요. 진지한 개선이 필요합니다." },
  { minSavageCount: 5, template: "이 레포는 적신호예요. 빨리 대응하세요." },
  { minSavageCount: 5, template: "코드 품질이 우려 수준이에요." },
  { minSavageCount: 5, template: "이 레포를 방치하면 상황이 더 나빠져요." },
  { minSavageCount: 5, template: "날카로운 피드백이 많았지만 모두 사실이에요." },
  { minSavageCount: 5, template: "리팩토링 없이는 이 프로젝트의 미래가 암울해요." },
  { minSavageCount: 5, template: "이 레포에 대해 진지한 대화가 필요해요." },
  { minSavageCount: 5, template: "기술 부채가 위험 수준이에요. 즉시 대응하세요." },
  { minSavageCount: 5, template: "이 정도면 팀 전체가 문제를 인지해야 해요." },
  { minSavageCount: 5, template: "코드가 도움을 요청하고 있어요. 응답해주세요." },

  // minSavageCount: 6 — 추가
  { minSavageCount: 6, template: "D 등급. 심각한 상황이에요." },
  { minSavageCount: 6, template: "이 레포는 응급 조치가 필요해요." },
  { minSavageCount: 6, template: "코드 품질이 바닥이에요. 끌어올려야 해요." },
  { minSavageCount: 6, template: "이 프로젝트는 구조적 문제가 있어요." },
  { minSavageCount: 6, template: "진지하게 '처음부터 다시 만들까'를 고민해야 해요." },
  { minSavageCount: 6, template: "이 레포의 기술 부채는 갚을 수 없는 수준에 근접했어요." },
  { minSavageCount: 6, template: "코드 리뷰, 테스트, 리팩토링... 전부 도입하세요." },
  { minSavageCount: 6, template: "이 프로젝트에서 좋은 점을 찾기가 어려웠어요." },
  { minSavageCount: 6, template: "날카로운 로스팅의 연속이었지만 현실이에요." },
  { minSavageCount: 6, template: "이 레포를 개선하려면 팀 전체의 노력이 필요해요." },

  // minSavageCount: 7 — 추가
  { minSavageCount: 7, template: "D- 등급. 사실상 낙제예요." },
  { minSavageCount: 7, template: "이 레포는 구제 불능의 경계에 서 있어요." },
  { minSavageCount: 7, template: "혹독한 로스팅이었지만 이건 사랑이에요. 독한 사랑." },
  { minSavageCount: 7, template: "코드를 보면서 한숨만 나왔어요." },
  { minSavageCount: 7, template: "이 프로젝트를 살리려면 엄청난 노력이 필요해요." },
  { minSavageCount: 7, template: "기술 부채가 은하계 수준이에요." },
  { minSavageCount: 7, template: "이 레포의 유일한 희망: 대규모 재건축." },
  { minSavageCount: 7, template: "이 정도면 이력서에서 이 프로젝트를 빼시는 게..." },
  { minSavageCount: 7, template: "코드가 '제발 날 리팩토링해줘'라고 울고 있어요." },
  { minSavageCount: 7, template: "이 레포에서 일하는 건 수행이에요. 고행." },

  // minSavageCount: 8 — 추가
  { minSavageCount: 8, template: "F 등급. 재수강 아니라 전과를 고려하세요." },
  { minSavageCount: 8, template: "이 레포를 보면서 인류의 한계를 느꼈어요." },
  { minSavageCount: 8, template: "혹독한 로스팅도 이 레포의 상태를 다 표현 못해요." },
  { minSavageCount: 8, template: "이 코드베이스는 생물학적 무기 수준이에요." },
  { minSavageCount: 8, template: "이 레포를 유지보수하시는 분께 진심으로 위로를 전해요." },
  { minSavageCount: 8, template: "코드가 이 정도면 삭제하고 다시 시작하는 게 빠를 거예요." },
  { minSavageCount: 8, template: "이 프로젝트는 개발의 모든 안티패턴을 보여줘요." },
  { minSavageCount: 8, template: "이 레포를 clone하면 컴퓨터가 항의해요." },
  { minSavageCount: 8, template: "역대급 혹독한 로스팅! 그만큼 역대급으로 나쁜 레포." },
  { minSavageCount: 8, template: "이 코드를 본 후 10분간 명상이 필요했어요." },

  // minSavageCount: 9 — 추가
  { minSavageCount: 9, template: "F- 등급. 등급 시스템을 벗어났어요." },
  { minSavageCount: 9, template: "전설적인 레포! 최악의 전설." },
  { minSavageCount: 9, template: "이 코드를 보면 프로그래밍을 발명한 사람이 후회할 거예요." },
  { minSavageCount: 9, template: "이 레포는 디지털 세계의 방사능 폐기물이에요." },
  { minSavageCount: 9, template: "코드 품질이 절대 영도(0K)에요. 더 이상 내려갈 수 없어요." },
  { minSavageCount: 9, template: "이 레포를 분석한 AI가 정신 건강 지원을 요청했어요." },
  { minSavageCount: 9, template: "역사에 남을 레포! 개발의 암흑 시대를 증언하는 유물." },
  { minSavageCount: 9, template: "이 코드베이스를 이해할 수 있는 존재는 이 우주에 없어요." },
  { minSavageCount: 9, template: "git-roast가 이 레포 때문에 PTSD에 걸렸어요." },
  { minSavageCount: 9, template: "이 레포는 '무한한 가능성' 중 최악의 가능성을 선택했어요." },

  // minSavageCount: 10 — 추가
  { minSavageCount: 10, template: "점수 매기기를 포기했어요. 스케일을 초월했으니까요." },
  { minSavageCount: 10, template: "이 레포는 우주적 규모의 재앙이에요." },
  { minSavageCount: 10, template: "코드를 보다가 눈에서 피가 났어요. (비유적으로)" },
  { minSavageCount: 10, template: "이 레포를 열면 'Abandon all hope, ye who enter here'가 나와야 해요." },
  { minSavageCount: 10, template: "git-roast 최종 판결: 이 레포는 디지털 세계에서 추방합니다." },
  { minSavageCount: 10, template: "인류 기술의 최저점을 목격했습니다. 이 레포 덕분에." },
  { minSavageCount: 10, template: "이 코드베이스를 타임캡슐에 넣으면 미래 인류가 공포에 떨 거예요." },
  { minSavageCount: 10, template: "이 레포는 컴퓨터 과학의 반증이에요. '과학'이 아니라 '혼돈'." },
  { minSavageCount: 10, template: "최종 결론: 이 레포는 전설이에요. 절대로 따라 하지 마세요." },
  { minSavageCount: 10, template: "git-roast가 당신의 레포를 보고 자아 성찰을 시작했어요. '내가 왜 존재하는 걸까...'" },

  // 추가: 다양한 minSavageCount 값에 대한 보충
  { minSavageCount: 0, template: "오늘의 분석 결과: 당신은 모범 개발자입니다!" },
  { minSavageCount: 0, template: "이 레포는 별 다섯 개 호텔처럼 깨끗해요." },
  { minSavageCount: 0, template: "코드 위생 상태: 수술실 수준의 청결함." },
  { minSavageCount: 0, template: "당신의 레포에서 문제를 찾으려 했지만 실패했어요." },
  { minSavageCount: 0, template: "이 레포는 git-roast의 천적이에요." },

  { minSavageCount: 1, template: "작은 흠이 있지만 전체적으로 훌륭해요." },
  { minSavageCount: 1, template: "95점! 나머지 5점은 쉽게 채울 수 있어요." },
  { minSavageCount: 1, template: "거의 완벽한 레포. 약간만 다듬으세요." },
  { minSavageCount: 1, template: "이 정도면 자랑스러운 레포예요." },
  { minSavageCount: 1, template: "한 가지만 빼면 다 완벽해요." },

  { minSavageCount: 2, template: "약간의 개선이 필요하지만 나쁘지 않아요." },
  { minSavageCount: 2, template: "85점! 조금만 노력하면 90점 이상이에요." },
  { minSavageCount: 2, template: "전반적으로 양호. 두 가지만 고치세요." },
  { minSavageCount: 2, template: "괜찮은 레포예요. 디테일만 좀 더 신경 쓰세요." },
  { minSavageCount: 2, template: "나쁘지 않지만 더 잘할 수 있어요." },

  { minSavageCount: 3, template: "70점! 보통 수준이에요. 개선의 여지가 많아요." },
  { minSavageCount: 3, template: "이 레포에 좀 더 관심을 기울이세요." },
  { minSavageCount: 3, template: "몇 가지 개선하면 확 달라질 거예요." },
  { minSavageCount: 3, template: "기본기는 있는데 실행력이 좀 부족해요." },
  { minSavageCount: 3, template: "이 레포를 업그레이드할 시간이에요." },

  { minSavageCount: 4, template: "60점. 기준선 아래예요. 노력이 필요합니다." },
  { minSavageCount: 4, template: "이 레포는 긴급 조치가 필요한 상태예요." },
  { minSavageCount: 4, template: "문제가 쌓이고 있어요. 지금 행동하세요." },
  { minSavageCount: 4, template: "이 정도면 '기술 부채 상환의 날'을 선포해야 해요." },
  { minSavageCount: 4, template: "진지한 리팩토링 계획이 필요합니다." },

  { minSavageCount: 5, template: "50점. 낙제 수준이에요. 빨리 개선하세요." },
  { minSavageCount: 5, template: "이 레포의 상태가 심각해요. 인지하고 계시죠?" },
  { minSavageCount: 5, template: "날카로운 로스팅이 많았지만 다 이유가 있었어요." },
  { minSavageCount: 5, template: "지금 이 순간이 변화의 기회예요." },
  { minSavageCount: 5, template: "이 레포를 살리려면 진심을 다해야 해요." },

  { minSavageCount: 6, template: "40점. 위험 수준이에요." },
  { minSavageCount: 6, template: "이 레포는 집중 치료실에 들어가야 해요." },
  { minSavageCount: 6, template: "기술 부채의 이자가 감당 안 되는 수준이에요." },
  { minSavageCount: 6, template: "진심으로 걱정되는 레포예요." },
  { minSavageCount: 6, template: "이 코드베이스를 살리려면 기적이 필요해요." },

  { minSavageCount: 7, template: "30점. 사실상 폐기 수준이에요." },
  { minSavageCount: 7, template: "이 레포를 보면 한숨만 나와요." },
  { minSavageCount: 7, template: "코드가 고통받고 있어요. 더 이상은 안 돼요." },
  { minSavageCount: 7, template: "이 프로젝트를 살릴 의지가 있으시다면... 응원합니다." },
  { minSavageCount: 7, template: "이 레포에서 '좋은 점'을 찾는 건 불가능했어요." },

  { minSavageCount: 8, template: "20점. 구제 불능에 가까워요." },
  { minSavageCount: 8, template: "이 레포는 교육용 반면교사 자료로만 가치가 있어요." },
  { minSavageCount: 8, template: "이 코드를 보면서 개발의 의미를 되짚어 봤어요." },
  { minSavageCount: 8, template: "이 프로젝트는 더 이상 '개선'이 아니라 '재건'이 필요해요." },
  { minSavageCount: 8, template: "혹독했지만 현실이에요. 받아들이시고 행동하세요." },

  { minSavageCount: 9, template: "10점. 존재 자체가 경고예요." },
  { minSavageCount: 9, template: "이 레포는 디지털 세계의 전설이 될 거예요." },
  { minSavageCount: 9, template: "코드 품질의 마리아나 해구. 바닥이 안 보여요." },
  { minSavageCount: 9, template: "이 레포를 본 후 프로그래밍의 의미를 다시 생각하게 됐어요." },
  { minSavageCount: 9, template: "전설적인 최악! 이보다 나쁠 순 없어요. 아마도." },

  { minSavageCount: 10, template: "0점. 측정 불가. 스케일 초과." },
  { minSavageCount: 10, template: "이 레포는 우주적 농담이에요. 근데 아무도 안 웃겨요." },
  { minSavageCount: 10, template: "코드의 종말! 이 레포는 모든 것의 끝이에요." },
  { minSavageCount: 10, template: "git-roast 역사상 최고의 로스팅 대상. 영광의(?) 1위." },
  { minSavageCount: 10, template: "이 레포를 보고 git-roast가 은퇴를 선언합니다. 더 이상 이길 수 없으니까요." },

  // 추가: 한국 개발 문화 관련 클로징
  { minSavageCount: 0, template: "한국 개발자의 자부심! 깔끔한 레포 감사합니다." },
  { minSavageCount: 1, template: "야근 없이도 이런 품질을 만드실 수 있다는 증거예요." },
  { minSavageCount: 2, template: "조금만 더 신경 쓰면 네카라쿠배 수준이에요." },
  { minSavageCount: 3, template: "기술 면접에서 이 레포를 보여주시려면 좀 정리가 필요해요." },
  { minSavageCount: 4, template: "이 레포로 포트폴리오 하시려면 리팩토링이 시급해요." },
  { minSavageCount: 5, template: "코딩 테스트보다 이 레포 정리가 더 급해요." },
  { minSavageCount: 6, template: "야근해서 만든 코드가 이 정도면... 일찍 퇴근하세요." },
  { minSavageCount: 7, template: "이 레포를 면접관이 보면 불합격 사유가 돼요." },
  { minSavageCount: 8, template: "한국 IT 역사의 어두운 면을 보여주는 레포." },
  { minSavageCount: 9, template: "이 레포가 한국 개발의 현실이라면... 슬프네요." },
  { minSavageCount: 10, template: "한국 IT의 가장 어두운 코너에서 발견된 전설의 레포." },

  // 추가: 유머/밈 관련 클로징
  { minSavageCount: 0, template: "이 레포는 'Works on every machine' 수준이에요." },
  { minSavageCount: 1, template: "'It works on my machine'이 아니라 진짜 어디서든 돌아갈 것 같아요." },
  { minSavageCount: 2, template: "Stack Overflow 없이도 만드신 것 같은 레포." },
  { minSavageCount: 3, template: "ChatGPT에게 코드 리뷰를 맡기시는 건 어떨까요?" },
  { minSavageCount: 4, template: "이 레포를 보면 '개발은 고통이다' 밈이 떠올라요." },
  { minSavageCount: 5, template: "'야 나두 코딩 배우려고' 하는 사람에게 이 레포를 보여주면 포기할 거예요." },
  { minSavageCount: 6, template: "이 레포에 필요한 것: Ctrl+Z 인생 버전." },
  { minSavageCount: 7, template: "'이 정도면 개발자 은퇴하셔야...'라고 말하고 싶지만 참을게요." },
  { minSavageCount: 8, template: "'야근해서 만든 코드가 이건가요?' 라는 말이 절로 나와요." },
  { minSavageCount: 9, template: "이 레포를 보면 '코딩 대신 치킨집'이라는 말이 이해돼요." },
  { minSavageCount: 10, template: "이 레포는 '세상에서 가장 슬픈 코드' 대회 1등감이에요." },

  // 추가: 격언/명언 패러디 클로징
  { minSavageCount: 0, template: "'좋은 코드는 좋은 습관에서 나온다.' 당신이 증명했어요." },
  { minSavageCount: 1, template: "'완벽은 세부사항에 있다.' 세부사항 하나만 고치세요." },
  { minSavageCount: 2, template: "'로마는 하루아침에 이루어지지 않았다.' 조금씩 개선하세요." },
  { minSavageCount: 3, template: "'시작이 반이다.' 그 반을 채우실 시간이에요." },
  { minSavageCount: 4, template: "'위기는 기회다.' 이 레포를 개선할 기회를 잡으세요." },
  { minSavageCount: 5, template: "'고통 없이 얻는 것은 없다.' 이 레포를 고치면 성장할 거예요." },
  { minSavageCount: 6, template: "'절망의 끝에 희망이 있다.' ... 정말요?" },
  { minSavageCount: 7, template: "'불가능은 없다.' 이 레포를 고치는 것은... 글쎄요." },
  { minSavageCount: 8, template: "'예술은 고통에서 태어난다.' 이 코드는 고통 그 자체." },
  { minSavageCount: 9, template: "'이것 또한 지나가리라.' 이 레포도 언젠간 archived 되겠죠." },
  { minSavageCount: 10, template: "'끝이 좋으면 다 좋다.' 끝이 보이지 않는다는 게 문제지만요." },
];
