import type { RoastTemplate } from "../../types.ts";

export const branchTemplates: RoastTemplate[] = [
  // ============================================================
  // 브랜치 0-1개 (main만 사용) — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 심플한 워크플로우시네요." },
  { id: "branch", severity: "mild", template: "main 하나로 가시는군요. 미니멀리스트!" },
  { id: "branch", severity: "mild", template: "브랜치가 {totalBranches}개뿐이라니. 깔끔하게 가시는 스타일." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 심플 이즈 베스트를 실천하시는군요." },
  { id: "branch", severity: "mild", template: "main만 쓰시는 건 용기 있는 선택이에요." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 복잡한 건 싫으신 타입이시죠?" },
  { id: "branch", severity: "mild", template: "단일 브랜치 전략이시군요. 소규모 프로젝트에는 적합해요." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 간결한 git 히스토리가 예상돼요." },
  { id: "branch", severity: "mild", template: "브랜치 하나로 충분하신 분. 심플한 프로젝트이시군요." },
  { id: "branch", severity: "mild", template: "main 브랜치만 있네요. Trunk-based Development?" },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 깔끔한 워크플로우예요." },
  { id: "branch", severity: "mild", template: "브랜치 전략이 단순해서 좋네요." },
  { id: "branch", severity: "mild", template: "main만 쓰시는 건 자신감의 표현이에요." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 혼자 개발하시면 이게 편하죠." },
  { id: "branch", severity: "mild", template: "단일 브랜치. 심플하고 효율적이에요." },

  // 브랜치 0-1개 — medium
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개... main에 직접 푸시하시는 건가요?" },
  { id: "branch", severity: "medium", template: "브랜치가 {totalBranches}개뿐이면 기능 개발할 때 어떻게 하시나요?" },
  { id: "branch", severity: "medium", template: "main 하나에 모든 걸 밀어 넣으시다니. PR 리뷰는 안 하시나요?" },
  { id: "branch", severity: "medium", template: "브랜치 전략이... 없으시군요. 전략 자체가." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치. 팀 프로젝트면 문제 될 수 있어요." },
  { id: "branch", severity: "medium", template: "main에 직접 커밋하시면 실수했을 때 되돌리기 힘들어요." },
  { id: "branch", severity: "medium", template: "브랜치 없이 개발하시면 main이 늘 불안정하지 않나요?" },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개. feature 브랜치라는 개념을 들어보셨나요?" },
  { id: "branch", severity: "medium", template: "main 직행 커밋... 코드 리뷰 문화가 없으시군요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치로 운영하시면 hotfix는 어떻게 하시나요?" },
  { id: "branch", severity: "medium", template: "브랜치 하나로 다 하시면 롤백이 지옥이에요." },
  { id: "branch", severity: "medium", template: "main에 직접 push... 보호 규칙(branch protection)은 안 쓰시나요?" },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개. git flow를 한번 검토해보시는 건?" },
  { id: "branch", severity: "medium", template: "feature 브랜치 없이 개발하시면 병렬 작업이 불가능해요." },
  { id: "branch", severity: "medium", template: "main 하나로 가시면 '이전 버전으로 돌아가기'가 고통이에요." },

  // 브랜치 0-1개 — savage
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개! main에 직접 push하는 건 프로덕션 러시안 룰렛이에요." },
  { id: "branch", severity: "savage", template: "브랜치가 {totalBranches}개라니! 이건 git을 쓰는 의미가 없어요." },
  { id: "branch", severity: "savage", template: "main 하나에 모든 걸! git을 Google Drive처럼 쓰시는 건가요?" },
  { id: "branch", severity: "savage", template: "브랜치 전략: 없음. 롤백 전략: 없음. 재앙 발생 확률: 100%." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치로 팀 프로젝트를 하시면 전쟁이 나요." },
  { id: "branch", severity: "savage", template: "main에 직접 push하시는 용기... 아니, 무모함이 대단하십니다." },
  { id: "branch", severity: "savage", template: "브랜치 하나로 운영하시면 장애 발생 시 '기도 메타'밖에 없어요." },
  { id: "branch", severity: "savage", template: "git branch를 한 번도 안 치신 것 같아요. 그게 뭔지는 아시죠?" },
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개! PR 없이 main에 바로? 이건 개발이 아니라 카미카제예요." },
  { id: "branch", severity: "savage", template: "main만 사용하시면 실수한 커밋이 바로 프로덕션이에요. 무섭지 않으세요?" },
  { id: "branch", severity: "savage", template: "브랜치 없이 협업하시면 머지 충돌로 팀이 해체돼요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치. 이건 버전 관리가 아니라 파일 백업이에요." },

  // 브랜치 0-1개 — legendary
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개! git을 dropbox처럼 쓰시는 전설의 개발자." },
  { id: "branch", severity: "legendary", template: "main 하나에 올인! 한 번의 실수로 모든 것이 무너질 수 있는 아슬아슬한 인생." },
  { id: "branch", severity: "legendary", template: "브랜치가 {totalBranches}개라니! 이건 git이 아니라 git add . && git push의 반복이에요." },
  { id: "branch", severity: "legendary", template: "브랜치 전략: 'main에 다 때려넣기'. 이건 전략이 아니라 무전략이에요." },
  { id: "branch", severity: "legendary", template: "main 직행 개발! 이 분의 모토: '브랜치는 약한 자가 만드는 것'." },
  { id: "branch", severity: "legendary", template: "{totalBranches}개 브랜치! git의 핵심 기능을 완벽하게 무시하시는 천재." },
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개! git init부터 git push까지 일직선. 갈림길이라곤 없는 인생." },
  { id: "branch", severity: "legendary", template: "main만 쓰시다니! 버전 관리의 의미를 완벽하게 부정하시는 반골 정신." },

  // ============================================================
  // 브랜치 5-10개 — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 적절한 수준이에요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 건강한 워크플로우예요." },
  { id: "branch", severity: "mild", template: "브랜치가 {totalBranches}개로 관리하기 좋은 수준이네요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 깔끔한 git 전략이에요." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 체계적으로 관리하시는군요." },
  { id: "branch", severity: "mild", template: "적절한 브랜치 수({totalBranches}개). 이상적인 워크플로우에요." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개라면 feature 브랜치를 잘 활용하시는 거네요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. PR 기반 개발을 하시는 것 같아요." },
  { id: "branch", severity: "mild", template: "브랜치 관리가 깔끔하시네요. {totalBranches}개." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 기본에 충실한 git 사용자." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치로 체계적인 개발 중이시군요." },
  { id: "branch", severity: "mild", template: "브랜치 수가 적절해요. {totalBranches}개면 딱 좋아요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 브랜치 전략을 잘 세우신 듯." },
  { id: "branch", severity: "mild", template: "적당한 브랜치 수. git을 잘 활용하시네요." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 무난하고 좋은 구성." },

  // 브랜치 5-10개 — medium (약간의 지적)
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개인데 머지 안 된 게 {unmergedCount}개... 좀 정리하세요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 중 {unmergedCount}개가 미머지? 브랜치 정리의 날이 필요해요." },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개. 괜찮은데 {unmergedCount}개는 왜 안 머지하셨어요?" },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치 중 살아있는 건 몇 개인가요?" },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개. 오래된 브랜치 정리는 하시나요?" },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치인데 네이밍이 좀 중구난방이에요." },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개. 적절한데 {unmergedCount}개가 방치 중이네요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치 중 활발한 건 반도 안 될 것 같아요." },
  { id: "branch", severity: "medium", template: "브랜치 관리는 하시는데 정리는 안 하시는 스타일?" },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치. 완료된 건 삭제하시는 게 좋아요." },

  // ============================================================
  // 브랜치 20개+ (나무 키우기) — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개! 활발한 개발이 진행 중이시군요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 큰 프로젝트이시네요." },
  { id: "branch", severity: "mild", template: "브랜치가 {totalBranches}개나! 많은 기능을 병렬로 개발 중이시군요." },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 팀이 크시거나 기능이 많으시거나." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 열심히 개발하시는 게 느껴져요." },
  { id: "branch", severity: "mild", template: "브랜치 수가 많네요({totalBranches}개). 활발한 프로젝트!" },
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 다양한 작업이 동시에 진행 중이시군요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개의 브랜치. 프로젝트가 잘 돌아가는 증거." },

  // 브랜치 20개+ — medium
  { id: "branch", severity: "medium", template: "브랜치가 {totalBranches}개?! 이건 나무가 아니라 숲이에요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치... 정리를 좀 하셔야 할 것 같아요." },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개. 이 중 실제로 활성인 건 몇 개예요?" },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치 중 머지 안 된 게 {unmergedCount}개... 정리 좀!" },
  { id: "branch", severity: "medium", template: "브랜치가 {totalBranches}개나 있으면 어떤 게 뭔지 기억이나 하세요?" },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치. git branch 치면 스크롤해야 하는 수준이에요." },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개. 브랜치 정리하는 것도 개발이에요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치를 다 기억하시는 건 아니시죠?" },
  { id: "branch", severity: "medium", template: "브랜치가 {totalBranches}개면 checkout할 때 자동완성이 필수겠네요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치. 이건 branching strategy가 아니라 branching chaos예요." },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개인데 {unmergedCount}개가 미머지면 좀 심각해요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치. 절반은 이미 죽은 브랜치 아닌가요?" },
  { id: "branch", severity: "medium", template: "브랜치를 만들기만 하고 삭제를 안 하시는 타입이시군요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치... 브랜치 네이밍 규칙은 있으시죠?" },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개. 이 중 3개월 이상 된 건 삭제하세요." },

  // 브랜치 20개+ — savage
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개! 이건 git이 아니라 브랜치 농장이에요!" },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치?! git branch 치면 터미널이 폭발하겠네요." },
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개! 브랜치 하나당 커밋이 1개인 건 아니죠?" },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치를 관리하시다니. 아, 관리를 안 하시는 거군요." },
  { id: "branch", severity: "savage", template: "브랜치가 {totalBranches}개면 이건 나무가 아니라 정글이에요!" },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치! 브랜치를 만드는 게 취미이신 건가요?" },
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개! 화석이 된 브랜치가 절반은 되겠어요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치에 {unmergedCount}개 미머지! 이건 재앙이에요." },
  { id: "branch", severity: "savage", template: "브랜치가 {totalBranches}개나 있는데 어떤 게 최신인지 아시나요?" },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치! 깃 그래프 그리면 거미줄 같겠네요." },
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개! 이 프로젝트의 git log는 스파게티 코드보다 복잡해요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개의 브랜치를 보면 이 프로젝트의 혼돈이 느껴져요." },
  { id: "branch", severity: "savage", template: "브랜치를 {totalBranches}개나 만들어놓고 대부분 방치하셨죠?" },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치! 'git branch -d'를 모르시는 건 아니시죠?" },
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개! 이건 version control이 아니라 chaos control이에요." },

  // 브랜치 20개+ — legendary
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개! 이건 git repository가 아니라 브랜치 묘지예요." },
  { id: "branch", severity: "legendary", template: "{totalBranches}개 브랜치! 아마존 열대우림보다 브랜치가 많으시네요." },
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개! 각 브랜치마다 유서가 필요한 수준." },
  { id: "branch", severity: "legendary", template: "{totalBranches}개의 브랜치! 이건 git tree가 아니라 git forest예요." },
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개! 기네스북에 '가장 많은 브랜치'로 등록하세요." },
  { id: "branch", severity: "legendary", template: "{totalBranches}개 브랜치! 이 레포의 git graph를 시각화하면 추상화 작품이 완성돼요." },
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개! 브랜치마다 다른 세계가 열리겠네요. 멀티버스인가요?" },
  { id: "branch", severity: "legendary", template: "{totalBranches}개 브랜치! 이 레포 clone하면 디스크 공간이 사라져요." },

  // ============================================================
  // 머지 안 된 브랜치 수 — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "미머지 브랜치 {unmergedCount}개. 아직 작업 중이시겠죠?" },
  { id: "branch", severity: "mild", template: "머지 안 된 브랜치가 {unmergedCount}개 있네요. 곧 정리하시겠죠?" },
  { id: "branch", severity: "mild", template: "{unmergedCount}개 브랜치가 미머지 상태. 진행 중인 작업이 많으시군요." },
  { id: "branch", severity: "mild", template: "미머지 {unmergedCount}개. 개발이 활발하시네요." },
  { id: "branch", severity: "mild", template: "{unmergedCount}개 미머지 브랜치. 완료되면 정리해주세요." },
  { id: "branch", severity: "mild", template: "아직 머지 안 된 브랜치가 {unmergedCount}개. 열심히 하시는군요." },
  { id: "branch", severity: "mild", template: "미머지 브랜치 {unmergedCount}개. 진행 중인 feature가 많으시네요." },
  { id: "branch", severity: "mild", template: "{unmergedCount}개 브랜치가 대기 중. 리뷰 기다리시는 건가요?" },
  { id: "branch", severity: "mild", template: "미머지 {unmergedCount}개. 작업이 밀려있는 것 같네요." },
  { id: "branch", severity: "mild", template: "{unmergedCount}개 미머지. 곧 깔끔하게 정리되겠죠?" },
  { id: "branch", severity: "mild", template: "머지 대기 중 {unmergedCount}개. 바쁘신 거 이해해요." },
  { id: "branch", severity: "mild", template: "미머지 브랜치가 좀 있네요({unmergedCount}개). 시간 되실 때 정리를." },
  { id: "branch", severity: "mild", template: "{unmergedCount}개 브랜치 미머지. 코드 리뷰 중이시겠죠?" },
  { id: "branch", severity: "mild", template: "미머지 {unmergedCount}개. 곧 머지하실 거라 믿어요." },
  { id: "branch", severity: "mild", template: "아직 합쳐지지 않은 브랜치가 {unmergedCount}개. 화이팅!" },

  // 머지 안 된 브랜치 — medium
  { id: "branch", severity: "medium", template: "미머지 브랜치 {unmergedCount}개... 이거 다 살아있는 건가요?" },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 브랜치가 미머지 상태. 좀 정리하시는 게 좋겠어요." },
  { id: "branch", severity: "medium", template: "머지 안 된 게 {unmergedCount}개라니. 포기한 기능이 몇 개인가요?" },
  { id: "branch", severity: "medium", template: "미머지 {unmergedCount}개. 이 중 절반은 이미 필요 없는 거 아닌가요?" },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 미머지 브랜치. 리뷰어가 없으신 건가요, 리뷰를 안 받으시는 건가요?" },
  { id: "branch", severity: "medium", template: "미머지 브랜치 {unmergedCount}개. 이건 브랜치가 아니라 미완성 컬렉션이에요." },
  { id: "branch", severity: "medium", template: "{unmergedCount}개가 미머지면 main에 들어간 코드가 전부인 건가요?" },
  { id: "branch", severity: "medium", template: "미머지 {unmergedCount}개... 시작만 하고 완료를 못하시는 타입이신 건 아닌지." },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 브랜치가 방치 중. WIP 브랜치의 무덤이네요." },
  { id: "branch", severity: "medium", template: "미머지 브랜치 {unmergedCount}개. 한 번에 정리하시면 상쾌하실 거예요." },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 미머지. 브랜치 청소의 날을 지정하세요." },
  { id: "branch", severity: "medium", template: "미머지 {unmergedCount}개... 이 중 머지할 만한 게 있긴 한가요?" },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 브랜치가 떠돌아다니고 있어요. 정착시켜 주세요." },
  { id: "branch", severity: "medium", template: "미머지 브랜치 {unmergedCount}개. 각각의 브랜치에 슬픈 사연이 있겠네요." },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 미머지. 혹시 머지하는 법을 모르시는 건 아니시죠?" },

  // 머지 안 된 브랜치 — savage
  { id: "branch", severity: "savage", template: "미머지 {unmergedCount}개! 이건 브랜치가 아니라 포기한 꿈의 잔해예요." },
  { id: "branch", severity: "savage", template: "{unmergedCount}개 미머지 브랜치! 시작만 하고 끝내지 못하는 당신의 인생 축소판." },
  { id: "branch", severity: "savage", template: "미머지 브랜치 {unmergedCount}개! 이 중 6개월 이상 된 건 화석이에요." },
  { id: "branch", severity: "savage", template: "{unmergedCount}개가 미머지면 이건 개발이 아니라 브랜치 수집이에요." },
  { id: "branch", severity: "savage", template: "미머지 {unmergedCount}개! 포기한 feature 브랜치들이 무덤에서 울고 있어요." },
  { id: "branch", severity: "savage", template: "{unmergedCount}개 브랜치가 미머지... 이건 기술 부채가 아니라 기술 빚더미예요." },
  { id: "branch", severity: "savage", template: "미머지 브랜치 {unmergedCount}개! merge conflict가 무서워서 안 하시는 거죠?" },
  { id: "branch", severity: "savage", template: "{unmergedCount}개 미머지! 브랜치를 만들고 잊어버리시는 게 특기이시군요." },
  { id: "branch", severity: "savage", template: "미머지 {unmergedCount}개! 이 브랜치들은 main을 영원히 보지 못할 운명." },
  { id: "branch", severity: "savage", template: "{unmergedCount}개 브랜치가 미머지! 이건 PR을 올리고 스스로 approve 안 하시는 건가요?" },
  { id: "branch", severity: "savage", template: "미머지 브랜치 {unmergedCount}개! 'git branch -D'가 약이에요." },
  { id: "branch", severity: "savage", template: "{unmergedCount}개 미머지! 이 브랜치들이 머지되는 날은 오지 않을 것 같아요." },
  { id: "branch", severity: "savage", template: "미머지 {unmergedCount}개! 이건 개발 진행이 아니라 개발 정체예요." },
  { id: "branch", severity: "savage", template: "{unmergedCount}개 미머지 브랜치. 절반은 이미 conflict가 해결 불가능할 듯." },
  { id: "branch", severity: "savage", template: "미머지 브랜치 {unmergedCount}개! 코드가 여기저기 흩어져 있어요." },

  // 머지 안 된 브랜치 — legendary
  { id: "branch", severity: "legendary", template: "미머지 {unmergedCount}개! 이건 레포가 아니라 미완성 프로젝트의 묘지예요." },
  { id: "branch", severity: "legendary", template: "{unmergedCount}개 미머지! 각 브랜치가 '나를 잊지 말아줘'라고 외치고 있어요." },
  { id: "branch", severity: "legendary", template: "미머지 브랜치 {unmergedCount}개! 이걸 다 머지하면 conflict 해결에 한 달 걸릴 거예요." },
  { id: "branch", severity: "legendary", template: "{unmergedCount}개의 미머지 브랜치! 이건 git repository의 호텔 캘리포니아예요. 체크인은 가능하지만 체크아웃은..." },
  { id: "branch", severity: "legendary", template: "미머지 {unmergedCount}개! 당신의 git graph는 세계 지도보다 복잡해요." },
  { id: "branch", severity: "legendary", template: "{unmergedCount}개 미머지 브랜치! 이건 개발이 아니라 브랜치 사육이에요." },
  { id: "branch", severity: "legendary", template: "미머지 브랜치 {unmergedCount}개! 이 수를 줄이는 것만으로도 3일은 걸리겠네요." },
  { id: "branch", severity: "legendary", template: "{unmergedCount}개의 미머지! 이 브랜치들을 합치면 새로운 프로젝트가 탄생할 거예요." },

  // ============================================================
  // 이상한 브랜치 이름 (test, asdf, fix-fix-fix) — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "이상한 이름의 브랜치가 {weirdNameCount}개 있네요. 좀 정리하시면 좋겠어요." },
  { id: "branch", severity: "mild", template: "브랜치 이름 중 좀 독특한 게 {weirdNameCount}개 보여요." },
  { id: "branch", severity: "mild", template: "이름이 좀 특이한 브랜치가 {weirdNameCount}개. 의미 있는 이름으로 바꾸시는 건?" },
  { id: "branch", severity: "mild", template: "브랜치 이름 {weirdNameCount}개가 좀 알쏭달쏭해요." },
  { id: "branch", severity: "mild", template: "이상한 브랜치 이름 {weirdNameCount}개. 급하게 만드셨나 봐요." },
  { id: "branch", severity: "mild", template: "브랜치명이 좀 즉흥적인 게 {weirdNameCount}개 있네요." },
  { id: "branch", severity: "mild", template: "이름만으로 용도를 모르는 브랜치가 {weirdNameCount}개." },
  { id: "branch", severity: "mild", template: "브랜치 네이밍에 좀 더 신경 쓰시면 좋겠어요({weirdNameCount}개)." },
  { id: "branch", severity: "mild", template: "독특한 브랜치 이름 {weirdNameCount}개. 개성이 넘치시네요." },
  { id: "branch", severity: "mild", template: "브랜치 이름 중 {weirdNameCount}개가 좀 모호해요." },
  { id: "branch", severity: "mild", template: "이상한 이름의 브랜치 {weirdNameCount}개. 나중에 정리해주세요." },
  { id: "branch", severity: "mild", template: "브랜치명이 좀 자유로운 게 {weirdNameCount}개 보여요." },

  // 이상한 브랜치 이름 — medium
  { id: "branch", severity: "medium", template: "이상한 브랜치 이름 {weirdNameCount}개... 'test', 'asdf' 같은 거 아닌가요?" },
  { id: "branch", severity: "medium", template: "브랜치 이름이 {weirdNameCount}개나 이상해요. 네이밍 컨벤션이 없으시군요." },
  { id: "branch", severity: "medium", template: "{weirdNameCount}개 브랜치 이름이 의미불명... 3개월 후에 본인도 모르실 거예요." },
  { id: "branch", severity: "medium", template: "이상한 이름 {weirdNameCount}개. 'fix-fix-fix'나 'temp-temp' 같은 거 있으시죠?" },
  { id: "branch", severity: "medium", template: "브랜치 이름 {weirdNameCount}개가 의미불명이에요. 미래의 당신을 위해 제대로 짓세요." },
  { id: "branch", severity: "medium", template: "{weirdNameCount}개의 이상한 브랜치명. 'aaa', 'zzz' 같은 거 있으면 삭제하세요." },
  { id: "branch", severity: "medium", template: "이상한 이름 브랜치 {weirdNameCount}개. 브랜치 이름도 코드 품질의 일부예요." },
  { id: "branch", severity: "medium", template: "브랜치 이름이 {weirdNameCount}개나 이상하면 협업할 때 혼란이 올 거예요." },
  { id: "branch", severity: "medium", template: "{weirdNameCount}개의 브랜치 이름이 암호 같아요. 해독이 필요해요." },
  { id: "branch", severity: "medium", template: "이상한 이름 {weirdNameCount}개. feature/, bugfix/ 같은 프리픽스를 쓰시는 건 어떨까요?" },
  { id: "branch", severity: "medium", template: "브랜치 네이밍이 {weirdNameCount}개나 엉망이면 팀원이 울어요." },
  { id: "branch", severity: "medium", template: "{weirdNameCount}개 이상한 브랜치명. 이거 다 임시로 만든 거죠?" },
  { id: "branch", severity: "medium", template: "이상한 이름의 브랜치 {weirdNameCount}개. 정리는 개발의 반이에요." },
  { id: "branch", severity: "medium", template: "브랜치 이름 {weirdNameCount}개가 이해 불가. 작명 센스를 기르세요." },
  { id: "branch", severity: "medium", template: "{weirdNameCount}개 브랜치 이름이 'help'를 외치고 있어요." },

  // 이상한 브랜치 이름 — savage
  { id: "branch", severity: "savage", template: "이상한 이름 {weirdNameCount}개! 'test123', 'asdfasdf', 'ㅋㅋㅋ' 같은 거 있으시죠?" },
  { id: "branch", severity: "savage", template: "브랜치 이름 {weirdNameCount}개가 쓰레기! 이건 네이밍이 아니라 키보드 랜덤 입력이에요." },
  { id: "branch", severity: "savage", template: "{weirdNameCount}개의 의미불명 브랜치! 브랜치 이름짓기도 실력이에요, 그리고 당신은 F." },
  { id: "branch", severity: "savage", template: "이상한 이름 {weirdNameCount}개! 당신의 브랜치 이름 = 고양이가 키보드 위를 걸어간 결과." },
  { id: "branch", severity: "savage", template: "브랜치 이름이 {weirdNameCount}개나 이상해요! 'final', 'final-final', 'real-final' 시리즈?" },
  { id: "branch", severity: "savage", template: "{weirdNameCount}개의 괴상한 브랜치명! 이건 git이 아니라 이름 짓기 실패 모음이에요." },
  { id: "branch", severity: "savage", template: "이상한 이름 {weirdNameCount}개! 브랜치 이름에 한국어를 쓰시는 건 아니시죠?" },
  { id: "branch", severity: "savage", template: "브랜치 이름 {weirdNameCount}개가 해독 불가! 로제타 스톤이 필요해요." },
  { id: "branch", severity: "savage", template: "{weirdNameCount}개의 브랜치가 '나는 임시입니다'라고 외치고 있어요. 6개월째." },
  { id: "branch", severity: "savage", template: "이상한 이름 {weirdNameCount}개! 'DO-NOT-DELETE'라는 이름의 브랜치가 가장 먼저 삭제 대상이에요." },
  { id: "branch", severity: "savage", template: "브랜치 이름이 {weirdNameCount}개나 이상하면 이건 네이밍 컨벤션이 '랜덤'인 거예요." },
  { id: "branch", severity: "savage", template: "{weirdNameCount}개 이상한 이름! 'hotfix-hotfix-hotfix'라는 이름이 있을 것 같아요." },

  // 이상한 브랜치 이름 — legendary
  { id: "branch", severity: "legendary", template: "이상한 이름 {weirdNameCount}개! 이건 브랜치 목록이 아니라 금지어 사전이에요." },
  { id: "branch", severity: "legendary", template: "브랜치 이름 {weirdNameCount}개가 전설적으로 이상해요. 후세에 길이 남을 작명이에요." },
  { id: "branch", severity: "legendary", template: "{weirdNameCount}개의 괴상한 브랜치명! 이건 git art인가요? 현대 미술?" },
  { id: "branch", severity: "legendary", template: "이상한 이름 {weirdNameCount}개! 'please-work', 'why-not-working', 'i-give-up' 시리즈?" },
  { id: "branch", severity: "legendary", template: "브랜치 이름 {weirdNameCount}개가 이상해서 이건 레포가 아니라 인터넷 밈 모음이에요." },
  { id: "branch", severity: "legendary", template: "{weirdNameCount}개의 전설적인 브랜치명! 'fix-fix-fix-fix-final-v2-real'이 있을 거예요." },

  // ============================================================
  // 브랜치 이름이 너무 긴 경우 — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "가장 긴 브랜치 이름: '{longestBranchName}'. 좀 길긴 하네요." },
  { id: "branch", severity: "mild", template: "브랜치 이름 '{longestBranchName}'가 좀 길어요." },
  { id: "branch", severity: "mild", template: "긴 브랜치 이름이 있네요: '{longestBranchName}'. 요약이 필요해요." },
  { id: "branch", severity: "mild", template: "'{longestBranchName}'... 브랜치 이름이 좀 구체적이시네요." },
  { id: "branch", severity: "mild", template: "가장 긴 브랜치명 '{longestBranchName}'. 설명이 충분하긴 하네요." },
  { id: "branch", severity: "mild", template: "브랜치 이름 '{longestBranchName}'가 자기소개서 같아요." },
  { id: "branch", severity: "mild", template: "'{longestBranchName}'... 브랜치 이름이 커밋 메시지보다 길어요." },
  { id: "branch", severity: "mild", template: "긴 브랜치 이름 '{longestBranchName}'. 핵심만 담아주세요." },

  // 브랜치 이름이 너무 긴 경우 — medium
  { id: "branch", severity: "medium", template: "'{longestBranchName}'... 이건 브랜치 이름이 아니라 소설 제목이에요." },
  { id: "branch", severity: "medium", template: "가장 긴 브랜치명 '{longestBranchName}'. checkout 치다가 손목 나가겠어요." },
  { id: "branch", severity: "medium", template: "'{longestBranchName}' 브랜치... Tab 자동완성 없으면 불가능한 이름." },
  { id: "branch", severity: "medium", template: "브랜치 이름이 '{longestBranchName}'라니. URL이 두 줄이겠어요." },
  { id: "branch", severity: "medium", template: "'{longestBranchName}'... 이 정도면 브랜치 이름에 README를 넣으신 거예요." },
  { id: "branch", severity: "medium", template: "가장 긴 브랜치명: '{longestBranchName}'. 줄임말을 좀 쓰세요." },
  { id: "branch", severity: "medium", template: "'{longestBranchName}'... 이 브랜치 이름을 외울 수 있는 사람은 없어요." },
  { id: "branch", severity: "medium", template: "브랜치 이름 '{longestBranchName}'가 커밋 메시지보다 설명적이에요." },
  { id: "branch", severity: "medium", template: "'{longestBranchName}'... 이건 브랜치명이 아니라 JIRA 티켓 설명이에요." },
  { id: "branch", severity: "medium", template: "가장 긴 브랜치명 '{longestBranchName}'. 터미널 한 줄을 차지하겠네요." },
  { id: "branch", severity: "medium", template: "'{longestBranchName}'... 이 정도 길이면 git branch 했을 때 줄바꿈 돼요." },
  { id: "branch", severity: "medium", template: "브랜치 이름이 이렇게 길면 복사-붙여넣기가 필수예요." },

  // 브랜치 이름이 너무 긴 경우 — savage
  { id: "branch", severity: "savage", template: "'{longestBranchName}'! 이건 브랜치 이름이 아니라 에세이예요!" },
  { id: "branch", severity: "savage", template: "가장 긴 브랜치명 '{longestBranchName}'. 이걸 치려면 타이핑 속도가 200 WPM이어야 해요." },
  { id: "branch", severity: "savage", template: "'{longestBranchName}'... 이 브랜치 이름을 다 읽으면 5초가 걸려요." },
  { id: "branch", severity: "savage", template: "브랜치 이름 '{longestBranchName}'! 이건 이름이 아니라 변명이에요." },
  { id: "branch", severity: "savage", template: "'{longestBranchName}'... 이렇게 긴 이름은 파일 경로 제한에 걸릴 수도 있어요." },
  { id: "branch", severity: "savage", template: "가장 긴 브랜치명 '{longestBranchName}'. Windows에서 clone하면 터져요." },
  { id: "branch", severity: "savage", template: "'{longestBranchName}'! 이름만으로 PR description이 완성되겠네요." },
  { id: "branch", severity: "savage", template: "브랜치 이름 '{longestBranchName}'! 이 정도면 이름에 커밋 로그가 포함된 거 아닌가요?" },
  { id: "branch", severity: "savage", template: "'{longestBranchName}'... 이름이 이렇게 길면 오타 확률 100%." },
  { id: "branch", severity: "savage", template: "가장 긴 브랜치명 '{longestBranchName}'. 이름 짓는 데만 5분 쓰셨죠?" },

  // 브랜치 이름이 너무 긴 경우 — legendary
  { id: "branch", severity: "legendary", template: "'{longestBranchName}'! 이건 브랜치 이름이 아니라 소설의 첫 장이에요." },
  { id: "branch", severity: "legendary", template: "가장 긴 브랜치명 '{longestBranchName}'. 이 이름으로 SEO 최적화가 가능할 듯." },
  { id: "branch", severity: "legendary", template: "'{longestBranchName}'! 이 브랜치 이름을 읽는 데 산소가 부족해요." },
  { id: "branch", severity: "legendary", template: "브랜치 이름 '{longestBranchName}'! 세계 기록 도전인가요?" },
  { id: "branch", severity: "legendary", template: "'{longestBranchName}'! 이 이름을 다 읽으면 퇴근 시간이에요." },

  // ============================================================
  // feature/bugfix/hotfix 네이밍 컨벤션 — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "feature/ 프리픽스를 쓰시네요. 좋은 네이밍 컨벤션이에요." },
  { id: "branch", severity: "mild", template: "bugfix/ 브랜치가 보이네요. 체계적으로 관리하시는군요." },
  { id: "branch", severity: "mild", template: "네이밍 컨벤션을 따르시는 것 같아요. 프로페셔널!" },
  { id: "branch", severity: "mild", template: "feature, bugfix, hotfix 프리픽스... 깔끔한 브랜치 전략." },
  { id: "branch", severity: "mild", template: "브랜치 네이밍이 일관적이에요. 팀 작업에 적합한 구조." },
  { id: "branch", severity: "mild", template: "feature/ 프리픽스를 쓰시다니. git flow를 알고 계시네요." },
  { id: "branch", severity: "mild", template: "브랜치 이름에 규칙이 있어 보여요. 좋은 습관." },
  { id: "branch", severity: "mild", template: "bugfix/ 프리픽스가 보이네요. 버그 추적이 쉬우시겠어요." },
  { id: "branch", severity: "mild", template: "hotfix/ 브랜치도 있네요. 긴급 수정 프로세스가 있으시군요." },
  { id: "branch", severity: "mild", template: "브랜치 네이밍 컨벤션이 있으시네요. 칭찬합니다." },

  // feature/bugfix/hotfix 네이밍 — medium
  { id: "branch", severity: "medium", template: "feature/ 브랜치가 많은데 bugfix/는 더 많네요. 버그 생산기?" },
  { id: "branch", severity: "medium", template: "hotfix 브랜치가 feature보다 많으면 뭔가 근본적인 문제가 있어요." },
  { id: "branch", severity: "medium", template: "feature/와 feat/가 혼용 중이시네요. 통일 좀 하세요." },
  { id: "branch", severity: "medium", template: "bugfix/ 브랜치 수가 feature/보다 많다는 건... 코드 품질 문제?" },
  { id: "branch", severity: "medium", template: "네이밍 컨벤션이 있다 없다 하시네요. 일관성이 필요해요." },
  { id: "branch", severity: "medium", template: "feature, fix, bugfix, hotfix, patch... 프리픽스가 너무 다양해요." },
  { id: "branch", severity: "medium", template: "hotfix가 이렇게 많으면 프로덕션이 불안정한 거 아닌가요?" },
  { id: "branch", severity: "medium", template: "feature/ 시작 브랜치가 {unmergedCount}개 미머지면 기능 완성을 못 하시는 거예요." },
  { id: "branch", severity: "medium", template: "브랜치 프리픽스가 중구난방이에요. 팀 내 규칙을 정하세요." },
  { id: "branch", severity: "medium", template: "bugfix/ 브랜치의 수가 당신의 코딩 실력을 말해주고 있어요." },
  { id: "branch", severity: "medium", template: "feature/를 쓰다 말고 그냥 이름만 쓰시는 브랜치도 보여요." },
  { id: "branch", severity: "medium", template: "hotfix/가 반복되면 이건 hotfix가 아니라 coldfix예요. 근본 원인을 고치세요." },

  // feature/bugfix/hotfix 네이밍 — savage
  { id: "branch", severity: "savage", template: "bugfix/ 브랜치가 feature/의 3배! 기능 하나 만들고 버그 3개 생산하시는 거죠?" },
  { id: "branch", severity: "savage", template: "hotfix가 이렇게 많으면 프로덕션이 항상 불타고 있는 거예요." },
  { id: "branch", severity: "savage", template: "feature/ 브랜치는 많은데 머지된 건 없어요. 기능 완성 능력: 0." },
  { id: "branch", severity: "savage", template: "네이밍 컨벤션이 없는 게 컨벤션이시군요. 카오스의 질서." },
  { id: "branch", severity: "savage", template: "bugfix 브랜치를 보면 당신의 코드가 얼마나 불안한지 알 수 있어요." },
  { id: "branch", severity: "savage", template: "hotfix/emergency, hotfix/critical, hotfix/urgent... 항상 위기 상황이시군요?" },
  { id: "branch", severity: "savage", template: "feature 브랜치가 전부 미머지면 이건 개발이 아니라 계획만 하는 거예요." },
  { id: "branch", severity: "savage", template: "bugfix/ 브랜치의 역사가 이 프로젝트의 고통의 역사를 증언해요." },
  { id: "branch", severity: "savage", template: "fix-fix, fix-fix-fix... 원본이 fix인데 fix의 fix가 필요하다니." },
  { id: "branch", severity: "savage", template: "hotfix의 hotfix가 있으면 이건 소프트웨어가 아니라 정크예요." },

  // feature/bugfix/hotfix 네이밍 — legendary
  { id: "branch", severity: "legendary", template: "bugfix/ 브랜치가 100개! 당신은 버그의 창조자이자 파괴자." },
  { id: "branch", severity: "legendary", template: "hotfix 브랜치만으로 깃 히스토리가 완성! 이건 소방서가 아니라 방화범이에요." },
  { id: "branch", severity: "legendary", template: "feature/ 0개 머지, bugfix/ 50개. 기능은 못 만들고 버그만 고치는 인생." },
  { id: "branch", severity: "legendary", template: "fix-fix-fix-final-real-this-time... 이 브랜치 이름이 당신의 고통을 대변해요." },
  { id: "branch", severity: "legendary", template: "hotfix 브랜치의 수가 feature 브랜치의 10배! 이건 개발이 아니라 소방 활동이에요." },

  // ============================================================
  // 날짜로 된 브랜치 (2024-01-01) — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "날짜로 된 브랜치가 보이네요. 버전 관리 방식이시군요." },
  { id: "branch", severity: "mild", template: "2024-xx-xx 형식의 브랜치... 날짜별 관리를 하시는 타입." },
  { id: "branch", severity: "mild", template: "날짜 기반 브랜치가 있네요. 나름의 시스템이 있으시군요." },
  { id: "branch", severity: "mild", template: "날짜 브랜치. 릴리즈 관리를 날짜로 하시나 봐요." },
  { id: "branch", severity: "mild", template: "날짜 형식 브랜치가 보여요. 체계적인 관리이시네요." },
  { id: "branch", severity: "mild", template: "날짜로 된 브랜치명. 시간순 관리를 좋아하시는 분." },
  { id: "branch", severity: "mild", template: "날짜 브랜치가 몇 개 있네요. 스프린트 기반이시군요." },
  { id: "branch", severity: "mild", template: "YYYY-MM-DD 형식의 브랜치. 캘린더 기반 개발." },

  // 날짜로 된 브랜치 — medium
  { id: "branch", severity: "medium", template: "날짜로 된 브랜치가 많네요. 이건 git이 아니라 다이어리인가요?" },
  { id: "branch", severity: "medium", template: "2024-01-01, 2024-01-02... 날짜 브랜치가 일기장 같아요." },
  { id: "branch", severity: "medium", template: "날짜 기반 브랜치... 이게 무슨 의미인지 다른 사람이 알 수 있나요?" },
  { id: "branch", severity: "medium", template: "날짜 브랜치를 쓰시면 무슨 작업인지 알 수가 없어요." },
  { id: "branch", severity: "medium", template: "날짜로 된 브랜치... 커밋 날짜랑 뭐가 다른 건가요?" },
  { id: "branch", severity: "medium", template: "날짜 브랜치가 매일 생기면 이건 브랜치가 아니라 캘린더." },
  { id: "branch", severity: "medium", template: "2024-xx-xx 브랜치들... 그날 뭘 했는지 기억하시나요?" },
  { id: "branch", severity: "medium", template: "날짜로 브랜치를 만들면 의미를 알 수 없어요. 설명적인 이름을 쓰세요." },
  { id: "branch", severity: "medium", template: "날짜 브랜치 다수... 이건 git log로 충분한 정보인데 왜 브랜치로?" },
  { id: "branch", severity: "medium", template: "날짜 기반 브랜치가 쌓이면 정리가 안 돼요." },

  // 날짜로 된 브랜치 — savage
  { id: "branch", severity: "savage", template: "날짜 브랜치 대량 발견! 이건 버전 관리가 아니라 날짜 관리예요." },
  { id: "branch", severity: "savage", template: "2024-01-01부터 2024-12-31까지 브랜치가 있으면 365개... 미쳤죠?" },
  { id: "branch", severity: "savage", template: "날짜로 된 브랜치... 이건 git을 달력처럼 쓰시는 거예요." },
  { id: "branch", severity: "savage", template: "날짜 브랜치가 이렇게 많으면 브랜치 목록이 달력이에요." },
  { id: "branch", severity: "savage", template: "날짜 브랜치는 아무 정보도 주지 않아요. 쓸모없는 이름의 정석." },
  { id: "branch", severity: "savage", template: "매일 새 날짜 브랜치를 만드시면 그건 커밋이지 브랜치가 아니에요." },
  { id: "branch", severity: "savage", template: "날짜 브랜치 전략! 이건 git branching strategy가 아니라 일기장 전략이에요." },
  { id: "branch", severity: "savage", template: "날짜로 된 브랜치... 'git log --oneline'이 하는 일을 브랜치로 하고 계시네요." },

  // 날짜로 된 브랜치 — legendary
  { id: "branch", severity: "legendary", template: "날짜 브랜치가 1년 치! 이건 git repository가 아니라 타임머신이에요." },
  { id: "branch", severity: "legendary", template: "365일 365개 브랜치! 매일 새 브랜치를 만드시는 전설의 일일 브랜치 장인." },
  { id: "branch", severity: "legendary", template: "날짜 브랜치의 끝판왕! git을 구글 캘린더로 쓰시는 분." },
  { id: "branch", severity: "legendary", template: "날짜 브랜치가 이렇게 많으면 git branch가 달력을 출력해요." },

  // ============================================================
  // 사람 이름으로 된 브랜치 — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "사람 이름으로 된 브랜치가 보이네요. 개인 작업 영역이시군요." },
  { id: "branch", severity: "mild", template: "이름 기반 브랜치가 있네요. 팀 내에서 영역을 나누셨나 봐요." },
  { id: "branch", severity: "mild", template: "개인 이름 브랜치... 소규모 팀에서 흔한 패턴이에요." },
  { id: "branch", severity: "mild", template: "사람 이름 브랜치. 누가 뭘 하는지 바로 알 수 있어서 편하죠." },
  { id: "branch", severity: "mild", template: "이름 브랜치가 보여요. 팀 협업 중이시군요." },
  { id: "branch", severity: "mild", template: "개인 브랜치가 있네요. 각자의 작업 공간이시군요." },

  // 사람 이름으로 된 브랜치 — medium
  { id: "branch", severity: "medium", template: "사람 이름 브랜치가 여러 개... 이건 팀 협업이 아니라 영토 분쟁이에요." },
  { id: "branch", severity: "medium", template: "이름 브랜치가 머지 안 되고 방치 중이면 그 사람 퇴사한 건 아닌가요?" },
  { id: "branch", severity: "medium", template: "사람 이름 브랜치... feature/기능명이 더 의미있어요." },
  { id: "branch", severity: "medium", template: "이름 기반 브랜치가 쌓이면 '이 코드 누가 짰어?'가 브랜치로 답이 되네요." },
  { id: "branch", severity: "medium", template: "개인 이름 브랜치... PR 없이 작업하시는 건 아니시죠?" },
  { id: "branch", severity: "medium", template: "사람 이름 브랜치가 미머지면 그 사람의 작업이 사라진 거예요." },
  { id: "branch", severity: "medium", template: "이름 브랜치는 코드 리뷰 문화가 없다는 증거일 수 있어요." },
  { id: "branch", severity: "medium", template: "개인 브랜치가 6개월 넘게 방치 중이면 그건 퇴사자의 유산이에요." },
  { id: "branch", severity: "medium", template: "사람 이름 브랜치... 기능 기반으로 바꾸시는 게 좋겠어요." },
  { id: "branch", severity: "medium", template: "이름 브랜치에서 바로 프로덕션에 배포하시는 건 아니시죠?" },

  // 사람 이름으로 된 브랜치 — savage
  { id: "branch", severity: "savage", template: "사람 이름 브랜치가 미머지! 그 사람 퇴사했는데 코드가 여기 남아있어요." },
  { id: "branch", severity: "savage", template: "이름 브랜치가 이렇게 많으면 이건 코드베이스가 아니라 인사 기록이에요." },
  { id: "branch", severity: "savage", template: "개인 이름 브랜치 + 미머지 = 전직 개발자의 유령이 떠도는 레포." },
  { id: "branch", severity: "savage", template: "사람 이름으로 브랜치를 만들면 그 사람이 떠나면 고아 브랜치가 돼요." },
  { id: "branch", severity: "savage", template: "이름 브랜치가 메인보다 커지면 이건 포크하신 거나 마찬가지예요." },
  { id: "branch", severity: "savage", template: "개인 브랜치에서 혼자 개발하시면 그건 협업이 아니라 독방 작업이에요." },
  { id: "branch", severity: "savage", template: "사람 이름 브랜치... 이건 팀워크가 아니라 각자도생이에요." },
  { id: "branch", severity: "savage", template: "이름 브랜치 3개가 전부 미머지면 팀원 3명이 각자 다른 방향으로 간 거예요." },

  // 사람 이름으로 된 브랜치 — legendary
  { id: "branch", severity: "legendary", template: "퇴사한 사람의 이름 브랜치가 가장 큰 브랜치! 이건 원한의 코드예요." },
  { id: "branch", severity: "legendary", template: "사람 이름 브랜치의 무덤! 여기에 묻힌 개발자들의 영혼이 느껴져요." },
  { id: "branch", severity: "legendary", template: "이름 브랜치가 전체의 절반! 이건 레포가 아니라 졸업앨범이에요." },
  { id: "branch", severity: "legendary", template: "개인 브랜치들이 영원히 머지되지 않을 운명! 브랜치의 저주." },

  // ============================================================
  // main/master 혼용 — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "main과 master가 둘 다 있네요. 마이그레이션 중이신가요?" },
  { id: "branch", severity: "mild", template: "main/master 둘 다 보여요. 정리가 필요해 보여요." },
  { id: "branch", severity: "mild", template: "master에서 main으로 옮기시는 중인 것 같네요." },
  { id: "branch", severity: "mild", template: "main과 master가 공존하는 레포. 과도기이시군요." },
  { id: "branch", severity: "mild", template: "main/master 혼용... 하나로 통일하시면 좋겠어요." },
  { id: "branch", severity: "mild", template: "두 개의 기본 브랜치가 보여요. 정리하시면 깔끔해질 거예요." },

  // main/master 혼용 — medium
  { id: "branch", severity: "medium", template: "main과 master가 둘 다 있으면 어떤 게 진짜인지 헷갈려요!" },
  { id: "branch", severity: "medium", template: "main/master 혼용은 혼란의 시작이에요. 하나를 삭제하세요." },
  { id: "branch", severity: "medium", template: "main과 master가 다른 내용이면 이건 심각한 문제예요." },
  { id: "branch", severity: "medium", template: "두 개의 기본 브랜치... 팀원들이 어디에 PR을 보내야 할지 모르겠어요." },
  { id: "branch", severity: "medium", template: "main/master 둘 다 있으면 CI/CD가 어디를 바라보는 건가요?" },
  { id: "branch", severity: "medium", template: "main과 master가 공존하면 배포가 혼란스러워요." },
  { id: "branch", severity: "medium", template: "main/master 혼용... 2024년인데 아직도 마이그레이션이 안 끝났나요?" },
  { id: "branch", severity: "medium", template: "두 개의 메인 브랜치는 하나가 너무 많아요." },
  { id: "branch", severity: "medium", template: "main과 master가 분기된 상태면 어떤 게 진실인지 모르겠어요." },
  { id: "branch", severity: "medium", template: "main/master 둘 다 살아있으면 프로덕션이 어딘지 아무도 몰라요." },

  // main/master 혼용 — savage
  { id: "branch", severity: "savage", template: "main과 master가 둘 다 있고 내용이 다르다면... 이건 재앙이에요!" },
  { id: "branch", severity: "savage", template: "main/master 혼용! 이건 브랜치 전략이 아니라 정체성 혼란이에요." },
  { id: "branch", severity: "savage", template: "두 개의 메인 브랜치! 하나는 진짜, 하나는 가짜. 어떤 게 진짜인지 당신도 모르시죠?" },
  { id: "branch", severity: "savage", template: "main과 master가 3개월째 각자의 길을 가고 있어요." },
  { id: "branch", severity: "savage", template: "main/master 혼용은 '어디에 배포하지?'라는 영원한 질문을 만들어요." },
  { id: "branch", severity: "savage", template: "두 개의 메인 브랜치! 이건 민주주의가 아니라 혼돈이에요." },
  { id: "branch", severity: "savage", template: "main과 master가 공존하는데 커밋이 다르다면 이건 평행 세계예요." },
  { id: "branch", severity: "savage", template: "main/master 혼용! rename 한 줄이면 끝나는 걸 몇 년째 미루고 계시네요." },

  // main/master 혼용 — legendary
  { id: "branch", severity: "legendary", template: "main과 master가 둘 다 있고 develop까지! 삼중 메인 브랜치의 전설." },
  { id: "branch", severity: "legendary", template: "main/master 혼용의 끝판왕! 누구도 진짜 메인을 모르는 슈뢰딩거의 레포." },
  { id: "branch", severity: "legendary", template: "main, master, develop, trunk 네 개 다 있으면 이건 미궁이에요." },
  { id: "branch", severity: "legendary", template: "main과 master의 전쟁! 어떤 브랜치가 프로덕션인지 모르는 사이 서비스가 다운." },

  // ============================================================
  // develop 브랜치 존재 여부 — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "develop 브랜치가 있네요. git flow를 따르시는군요." },
  { id: "branch", severity: "mild", template: "develop 브랜치 발견. 체계적인 브랜치 전략이에요." },
  { id: "branch", severity: "mild", template: "develop + main. git flow의 기본을 갖추셨네요." },
  { id: "branch", severity: "mild", template: "develop 브랜치가 있으시네요. 릴리즈 관리를 하시는군요." },
  { id: "branch", severity: "mild", template: "git flow 스타일이시군요. develop 브랜치가 보여요." },
  { id: "branch", severity: "mild", template: "develop 브랜치. 안정적인 배포 프로세스를 갖추셨네요." },

  // develop 브랜치 — medium
  { id: "branch", severity: "medium", template: "develop 브랜치가 있는데 main과 100커밋 이상 차이나면 문제예요." },
  { id: "branch", severity: "medium", template: "develop이 main보다 훨씬 앞서 있으면 배포를 안 하시는 거예요." },
  { id: "branch", severity: "medium", template: "develop 브랜치... 요즘은 trunk-based development가 대세인데." },
  { id: "branch", severity: "medium", template: "develop이 있는데 release 브랜치는 없으면 git flow가 반쪽이에요." },
  { id: "branch", severity: "medium", template: "develop 브랜치가 main보다 한참 앞서 있네요. 릴리즈 언제 하시나요?" },
  { id: "branch", severity: "medium", template: "develop이 있으면 main은 항상 배포 가능해야 하는데... 맞나요?" },
  { id: "branch", severity: "medium", template: "develop 브랜치가 방치 중이면 git flow를 포기하신 거예요." },
  { id: "branch", severity: "medium", template: "git flow를 쓰시는데 release 브랜치가 없으면 의미가 반감돼요." },
  { id: "branch", severity: "medium", template: "develop이 main과 너무 다르면 머지할 때 지옥을 맛보시게 돼요." },
  { id: "branch", severity: "medium", template: "develop 브랜치... 아직도 git flow 시대에 사시나요? 2024년이에요." },

  // develop 브랜치 — savage
  { id: "branch", severity: "savage", template: "develop이 main보다 200커밋 앞서면 이건 develop이 main이에요." },
  { id: "branch", severity: "savage", template: "develop 브랜치가 1년째 머지 안 되면 이건 develop이 아니라 abandon이에요." },
  { id: "branch", severity: "savage", template: "git flow를 하시면서 develop-main 머지를 안 하시면 flow가 막혀요." },
  { id: "branch", severity: "savage", template: "develop이 main과 500커밋 차이! 이건 브랜치가 아니라 포크예요." },
  { id: "branch", severity: "savage", template: "develop 브랜치의 존재 이유: 'main에 직접 push하면 안 되니까'. 근데 develop에 직접 push하시잖아요." },
  { id: "branch", severity: "savage", template: "develop이 너무 앞서가면 main이 레거시가 돼요. 이미 됐나요?" },
  { id: "branch", severity: "savage", template: "git flow를 선언했지만 실제로는 develop에 아무거나 push하는 카오스 flow." },
  { id: "branch", severity: "savage", template: "develop 브랜치가 main보다 건강하면 main의 존재 이유가 뭐예요?" },

  // develop 브랜치 — legendary
  { id: "branch", severity: "legendary", template: "develop이 main보다 1000커밋 앞서! 이건 develop이 사실상의 main이에요." },
  { id: "branch", severity: "legendary", template: "develop 브랜치가 2년째 머지 안 됨! 이건 브랜치가 아니라 타임캡슐이에요." },
  { id: "branch", severity: "legendary", template: "git flow를 완벽하게 무시하면서 develop만 있는 레포. 이건 no-flow예요." },
  { id: "branch", severity: "legendary", template: "develop-main 간 차이가 우주적! 이걸 머지하면 빅뱅이 일어날 거예요." },

  // ============================================================
  // 일반적인 브랜치 관련 추가 — mild
  // ============================================================
  { id: "branch", severity: "mild", template: "브랜치 관리가 깔끔하시네요. {totalBranches}개." },
  { id: "branch", severity: "mild", template: "좋은 브랜치 전략이에요. 유지하세요." },
  { id: "branch", severity: "mild", template: "브랜치 수가 적절하고 이름도 괜찮아요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 깔끔한 git 사용자시네요." },
  { id: "branch", severity: "mild", template: "브랜치 전략이 잘 세워져 있어요." },
  { id: "branch", severity: "mild", template: "git을 잘 활용하시는 분이시네요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 관리가 잘 되고 있어요." },
  { id: "branch", severity: "mild", template: "브랜치가 정돈되어 있네요. 칭찬합니다." },
  { id: "branch", severity: "mild", template: "깔끔한 브랜치 히스토리. 좋은 습관이에요." },
  { id: "branch", severity: "mild", template: "브랜치 네이밍이 일관적이에요. 프로답네요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치로 효율적인 개발 중." },
  { id: "branch", severity: "mild", template: "브랜치 전략이 교과서적이에요. 좋습니다." },
  { id: "branch", severity: "mild", template: "git 사용법을 잘 아시는 분." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 무난하고 좋아요." },
  { id: "branch", severity: "mild", template: "브랜치 관리 점수: B+. 좀 더 깔끔하게 가능하지만 괜찮아요." },
  { id: "branch", severity: "mild", template: "깔끔한 워크플로우. 브랜치가 잘 정리되어 있어요." },
  { id: "branch", severity: "mild", template: "브랜치 전략이 합리적이에요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 안정적인 개발 환경." },
  { id: "branch", severity: "mild", template: "좋은 git 습관이에요. 브랜치 관리가 깔끔합니다." },
  { id: "branch", severity: "mild", template: "브랜치가 보기 좋게 관리되고 있어요." },

  // 일반적인 추가 — medium
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개에 미머지 {unmergedCount}개... 정리 좀 하세요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치 중 활성은 얼마나 되나요?" },
  { id: "branch", severity: "medium", template: "브랜치 정리를 안 하시면 점점 카오스가 됩니다." },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 미머지. 좀 신경 써주세요." },
  { id: "branch", severity: "medium", template: "브랜치 관리에 좀 더 신경 쓰시면 좋겠어요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 중 {unmergedCount}개가 미머지면 비율이 좀 높아요." },
  { id: "branch", severity: "medium", template: "브랜치 정리의 날을 만드세요. 주 1회 추천." },
  { id: "branch", severity: "medium", template: "오래된 브랜치는 삭제하시는 게 정신 건강에 좋아요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치. 좀 줄이시면 관리가 편해질 거예요." },
  { id: "branch", severity: "medium", template: "브랜치 위생 상태: 보통. 개선의 여지가 있어요." },
  { id: "branch", severity: "medium", template: "머지된 브랜치는 바로 삭제하시는 게 좋아요." },
  { id: "branch", severity: "medium", template: "브랜치가 쌓이면 git이 무거워져요. 정리하세요." },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 미머지 브랜치를 방치하시면 안 돼요." },
  { id: "branch", severity: "medium", template: "브랜치 관리 점수: C. 좀 더 신경 쓰세요." },
  { id: "branch", severity: "medium", template: "활성 브랜치와 죽은 브랜치를 구분해서 정리해주세요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치. 반은 필요 없는 거 아닌가요?" },
  { id: "branch", severity: "medium", template: "브랜치를 만들면 책임지세요. 머지하거나 삭제하거나." },
  { id: "branch", severity: "medium", template: "미머지 브랜치 {unmergedCount}개. 이거 다 살아있는 건가요?" },
  { id: "branch", severity: "medium", template: "브랜치 위생 관리가 좀 필요해 보여요." },
  { id: "branch", severity: "medium", template: "이상한 이름 {weirdNameCount}개 + 미머지 {unmergedCount}개 = 혼돈의 레포." },

  // 일반적인 추가 — savage
  { id: "branch", severity: "savage", template: "브랜치 관리가 엉망이에요. {totalBranches}개 중 {unmergedCount}개 미머지." },
  { id: "branch", severity: "savage", template: "{weirdNameCount}개의 이상한 이름 + {unmergedCount}개 미머지 = 브랜치 재앙." },
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개에 정리는 0. 이건 방치예요." },
  { id: "branch", severity: "savage", template: "미머지 브랜치 {unmergedCount}개! 이건 개발이 아니라 브랜치 축적이에요." },
  { id: "branch", severity: "savage", template: "브랜치 관리 점수: F. 처음부터 다시 하세요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치의 혼돈! 질서라곤 없는 git 역사." },
  { id: "branch", severity: "savage", template: "이 레포의 브랜치 목록을 보면 두통이 와요." },
  { id: "branch", severity: "savage", template: "브랜치를 만들기만 하고 관리는 안 하시는 스타일이시군요." },
  { id: "branch", severity: "savage", template: "{unmergedCount}개 미머지! 이건 브랜치가 아니라 쓰레기통이에요." },
  { id: "branch", severity: "savage", template: "브랜치 정리를 한 번도 안 하신 게 느껴져요." },
  { id: "branch", severity: "savage", template: "이상한 이름 {weirdNameCount}개에 긴 이름에 미머지까지... 삼중고." },
  { id: "branch", severity: "savage", template: "git branch 결과가 스크롤해야 하는 양이면 문제가 있는 거예요." },
  { id: "branch", severity: "savage", template: "브랜치 관리 안 하면 나중에 'git log --graph'가 추상화가 돼요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치! 이걸 다 관리하시는 건 불가능해요." },
  { id: "branch", severity: "savage", template: "브랜치가 이렇게 엉망이면 새 팀원은 첫 날에 울어요." },
  { id: "branch", severity: "savage", template: "미머지 {unmergedCount}개, 이상한 이름 {weirdNameCount}개. 이건 git이 아니라 혼돈이에요." },
  { id: "branch", severity: "savage", template: "브랜치 위생 상태: 위험. 즉시 대청소가 필요해요." },
  { id: "branch", severity: "savage", template: "이 레포의 git graph를 프린트하면 벽지로 쓸 수 있어요." },
  { id: "branch", severity: "savage", template: "브랜치 관리 = 0. 이건 자유가 아니라 무정부 상태예요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치! 이건 나무가 아니라 잡초밭이에요." },

  // 일반적인 추가 — legendary
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개, 미머지 {unmergedCount}개! 이건 git의 종말이에요." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치 상태는 전설이에요. 나쁜 의미로." },
  { id: "branch", severity: "legendary", template: "브랜치 관리의 최악! 이건 교과서에 '이렇게 하면 안 됩니다'로 실릴 수준." },
  { id: "branch", severity: "legendary", template: "{totalBranches}개 브랜치의 지옥! 단테의 인페르노가 여기였군요." },
  { id: "branch", severity: "legendary", template: "브랜치 카오스의 왕좌에 앉으셨습니다. 아무도 이 혼돈을 해독할 수 없어요." },
  { id: "branch", severity: "legendary", template: "이 레포의 git graph는 세계 7대 불가사의에 등록될 수준이에요." },
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개! 각 브랜치가 평행 우주의 프로젝트를 담고 있어요." },
  { id: "branch", severity: "legendary", template: "미머지 {unmergedCount}개! 이 브랜치들을 머지하면 시공간이 왜곡돼요." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치 상태를 본 AI가 자기 확신을 잃었어요." },
  { id: "branch", severity: "legendary", template: "브랜치의 혼돈이 예술의 경지! 이건 git이 아니라 잭슨 폴록의 작품이에요." },

  // ============================================================
  // 추가 대량 템플릿: 한국 개발 문화 관련
  // ============================================================
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개. 한국 스타트업의 평균적인 수준이에요." },
  { id: "branch", severity: "mild", template: "브랜치 관리가 나쁘지 않아요. 국내 기준으로는 상위." },
  { id: "branch", severity: "medium", template: "브랜치 이름에 한국어가... 영어로 바꾸시는 게 좋겠어요." },
  { id: "branch", severity: "medium", template: "브랜치명 '급한수정', '임시'가 보여요. 영어로 써주세요." },
  { id: "branch", severity: "medium", template: "야근하면서 만든 브랜치 이름이 보여요. 'quick-fix-midnight'." },
  { id: "branch", severity: "savage", template: "브랜치 이름에 '제발'이 들어가면 이건 SOS 신호예요." },
  { id: "branch", severity: "savage", template: "'긴급', '급함', 'asap' 브랜치... 한국 IT의 현실이 느껴져요." },
  { id: "branch", severity: "savage", template: "브랜치 관리가 '빨리빨리' 문화의 피해자예요." },
  { id: "branch", severity: "legendary", template: "'야근-핫픽스' 브랜치! 한국 개발자의 애환이 담긴 전설의 브랜치명." },
  { id: "branch", severity: "legendary", template: "브랜치명에 '살려줘'가 있으면 이건 코드가 아니라 유서예요." },

  // ============================================================
  // 추가 변형들
  // ============================================================
  { id: "branch", severity: "mild", template: "브랜치 히스토리가 깔끔해요. 좋은 습관." },
  { id: "branch", severity: "mild", template: "git을 잘 활용하시는 것 같아 보여요." },
  { id: "branch", severity: "mild", template: "브랜치 워크플로우가 안정적이에요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 적절해요." },
  { id: "branch", severity: "mild", template: "브랜치 전략이 나쁘지 않아요." },
  { id: "branch", severity: "mild", template: "git 사용이 체계적이시네요." },
  { id: "branch", severity: "mild", template: "브랜치가 잘 정돈되어 있어요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 관리 잘하시네요." },
  { id: "branch", severity: "mild", template: "깔끔한 브랜치 구성입니다." },
  { id: "branch", severity: "mild", template: "브랜치 네이밍이 직관적이에요." },
  { id: "branch", severity: "mild", template: "좋은 워크플로우예요. 계속 유지하세요." },
  { id: "branch", severity: "mild", template: "브랜치 관리가 모범적이에요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치, 잘 정리되어 있네요." },
  { id: "branch", severity: "mild", template: "git 마스터시네요. 브랜치가 깔끔해요." },
  { id: "branch", severity: "mild", template: "브랜치 위생 상태: 양호. 잘하고 계세요." },

  { id: "branch", severity: "medium", template: "브랜치가 좀 산만해요. 정리를 추천합니다." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치... 좀 줄여보시는 건?" },
  { id: "branch", severity: "medium", template: "미머지 브랜치가 눈에 띄네요. {unmergedCount}개." },
  { id: "branch", severity: "medium", template: "브랜치 정리가 좀 필요한 시점이에요." },
  { id: "branch", severity: "medium", template: "오래된 브랜치를 정리하면 마음이 편해질 거예요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 중 쓸모없는 브랜치가 좀 보여요." },
  { id: "branch", severity: "medium", template: "브랜치 이름 좀 더 의미있게 지으시면 좋겠어요." },
  { id: "branch", severity: "medium", template: "정리 안 된 브랜치가 좀 거슬리네요." },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 미머지. 할 일 목록에 추가하세요." },
  { id: "branch", severity: "medium", template: "브랜치 위생 상태: 보통. 개선 가능해요." },
  { id: "branch", severity: "medium", template: "좀 지저분한 브랜치가 있네요. 정리하시죠." },
  { id: "branch", severity: "medium", template: "이상한 이름 {weirdNameCount}개. 의미있는 이름으로 바꾸세요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치인데 체계가 좀 부족해요." },
  { id: "branch", severity: "medium", template: "브랜치 관리에 좀 더 관심을 가져주세요." },
  { id: "branch", severity: "medium", template: "미머지 + 이상한 이름 = 브랜치 스파게티." },

  { id: "branch", severity: "savage", template: "이 레포의 브랜치 상태는 재난 수준이에요." },
  { id: "branch", severity: "savage", template: "브랜치 관리를 포기하셨다는 게 느껴져요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치 + {unmergedCount}개 미머지 = 혼돈의 레시피." },
  { id: "branch", severity: "savage", template: "브랜치를 만들 줄만 알고 지울 줄은 모르시는 거죠?" },
  { id: "branch", severity: "savage", template: "이 레포의 git graph는 미로보다 복잡해요." },
  { id: "branch", severity: "savage", template: "브랜치 상태가 쓰레기장이에요. 대청소 필수." },
  { id: "branch", severity: "savage", template: "{weirdNameCount}개 이상한 이름의 브랜치가 레포를 오염시키고 있어요." },
  { id: "branch", severity: "savage", template: "이 브랜치 목록을 보면 개발자의 고통이 느껴져요." },
  { id: "branch", severity: "savage", template: "브랜치 위생 상태: 위험. 격리 조치가 필요해요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치! 이건 git이 아니라 정글이에요." },

  { id: "branch", severity: "legendary", template: "이 레포의 브랜치 상태를 보면 git이 울어요." },
  { id: "branch", severity: "legendary", template: "브랜치의 종말! 이 레포는 git 역사의 가장 어두운 장이에요." },
  { id: "branch", severity: "legendary", template: "{totalBranches}개 브랜치의 무법지대! 법도 질서도 없는 git의 와일드 웨스트." },
  { id: "branch", severity: "legendary", template: "이 브랜치 목록을 후대에 전달하면 '이렇게 하면 안 됩니다' 교재가 돼요." },
  { id: "branch", severity: "legendary", template: "브랜치 카오스의 전설! 이 레포를 정리하면 노벨상 감이에요." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치를 시각화하면 잭슨 폴록이 질투할 거예요." },

  // ============================================================
  // 브랜치 전략 관련 추가
  // ============================================================
  { id: "branch", severity: "mild", template: "trunk-based development를 하시는 것 같네요. 모던한 접근." },
  { id: "branch", severity: "mild", template: "short-lived 브랜치를 쓰시는군요. 좋은 패턴이에요." },
  { id: "branch", severity: "mild", template: "PR 기반 워크플로우가 보여요. 코드 리뷰를 하시는군요." },
  { id: "branch", severity: "mild", template: "브랜치 수명이 짧은 편이에요. 좋은 습관." },
  { id: "branch", severity: "mild", template: "빠르게 만들고 빠르게 머지하시는 스타일이시군요." },

  { id: "branch", severity: "medium", template: "long-lived 브랜치가 많으면 머지 충돌의 씨앗이에요." },
  { id: "branch", severity: "medium", template: "브랜치 수명이 너무 길어요. 빨리 머지하세요." },
  { id: "branch", severity: "medium", template: "1주일 이상 된 브랜치는 stale한 거예요." },
  { id: "branch", severity: "medium", template: "브랜치를 오래 살려두면 main과의 간극이 벌어져요." },
  { id: "branch", severity: "medium", template: "빠르게 머지하고 빠르게 삭제하세요. 그게 답이에요." },

  { id: "branch", severity: "savage", template: "1개월 이상 된 브랜치는 이미 죽은 거예요. 장례를 치러주세요." },
  { id: "branch", severity: "savage", template: "long-lived 브랜치가 너무 많으면 이건 분산 개발이 아니라 분열이에요." },
  { id: "branch", severity: "savage", template: "브랜치가 main과 1년 이상 떨어지면 이건 다른 프로젝트예요." },
  { id: "branch", severity: "savage", template: "오래된 브랜치를 방치하는 건 코드의 시체를 방에 두는 거와 같아요." },
  { id: "branch", severity: "savage", template: "stale 브랜치가 fresh 브랜치보다 많으면 이건 레포의 노화예요." },

  { id: "branch", severity: "legendary", template: "가장 오래된 브랜치가 3년 전 것! 이건 브랜치가 아니라 타임캡슐이에요." },
  { id: "branch", severity: "legendary", template: "오래된 브랜치를 열어보면 고대 코드가 나와요. 디지털 고고학." },
  { id: "branch", severity: "legendary", template: "stale 브랜치가 90%! 이건 레포가 아니라 브랜치 화석관이에요." },

  // ============================================================
  // CI/CD와 브랜치 관련
  // ============================================================
  { id: "branch", severity: "mild", template: "브랜치별 CI가 돌아갈 것 같은 건강한 구조." },
  { id: "branch", severity: "medium", template: "브랜치가 많으면 CI 비용도 올라가요. 정리 좀 하세요." },
  { id: "branch", severity: "medium", template: "{totalBranches}개 브랜치에 다 CI를 돌리면 월 비용이..." },
  { id: "branch", severity: "savage", template: "브랜치마다 CI가 돌면 GitHub Actions 요금이 월급보다 비쌀 거예요." },
  { id: "branch", severity: "savage", template: "{totalBranches}개 브랜치의 CI 비용을 계산해보셨나요? 무서울 거예요." },
  { id: "branch", severity: "legendary", template: "브랜치마다 CI 파이프라인이 돌면 AWS 요금이 로켓처럼 치솟겠네요." },

  // ============================================================
  // 협업 패턴 관련
  // ============================================================
  { id: "branch", severity: "mild", template: "PR 기반 워크플로우가 보여요. 좋은 협업 문화." },
  { id: "branch", severity: "mild", template: "코드 리뷰를 위한 브랜치 전략이 잘 되어 있네요." },
  { id: "branch", severity: "medium", template: "리뷰 없이 머지하시는 브랜치가 있는 것 같아요." },
  { id: "branch", severity: "medium", template: "혼자 만들고 혼자 머지하시는 1인 개발 패턴이시네요." },
  { id: "branch", severity: "savage", template: "PR 리뷰 없이 머지하시면 브랜치 만드는 의미가 없어요." },
  { id: "branch", severity: "savage", template: "셀프 approve + 셀프 머지... 1인 극단이시군요." },
  { id: "branch", severity: "legendary", template: "PR 0개에 main 직행 커밋! 코드 리뷰? 그게 뭐죠?" },

  // 마지막 보충
  { id: "branch", severity: "mild", template: "브랜치 상태가 건강해요. 잘하고 계세요." },
  { id: "branch", severity: "mild", template: "git 워크플로우가 안정적이에요. 유지하세요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 적절하고 깔끔해요." },
  { id: "branch", severity: "mild", template: "브랜치 관리가 좋아요. 프로다운 git 사용." },
  { id: "branch", severity: "mild", template: "깔끔한 git 히스토리. 잘 관리하고 계시네요." },
  { id: "branch", severity: "medium", template: "브랜치 좀 정리하시면 더 좋을 거예요." },
  { id: "branch", severity: "medium", template: "미머지 브랜치 정리를 습관화하세요." },
  { id: "branch", severity: "medium", template: "브랜치 위생에 좀 더 신경 써주세요." },
  { id: "branch", severity: "medium", template: "{unmergedCount}개 미머지. 이번 주에 정리하시죠." },
  { id: "branch", severity: "medium", template: "브랜치 관리에 C 등급. 노력이 필요해요." },
  { id: "branch", severity: "savage", template: "이 브랜치 상태로는 팀 협업이 불가능해요." },
  { id: "branch", severity: "savage", template: "브랜치 관리를 포기한 레포. 구제 불능." },
  { id: "branch", severity: "savage", template: "이 레포의 브랜치를 보면 한숨이 나와요." },
  { id: "branch", severity: "savage", template: "브랜치 혼돈이 이 프로젝트의 품질을 대변해요." },
  { id: "branch", severity: "savage", template: "git을 이렇게 쓰면 Linus가 화내요." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치를 정리하면 세계 평화가 올 거예요." },
  { id: "branch", severity: "legendary", template: "브랜치 카오스의 대서사시! 영화로 만들면 3시간짜리." },
  { id: "branch", severity: "legendary", template: "이 레포의 git graph를 NFT로 팔면 현대 미술로 인정받겠어요." },
  { id: "branch", severity: "legendary", template: "브랜치의 전설! 이 레포는 git 역사에 길이 남을 거예요." },
  { id: "branch", severity: "legendary", template: "Linus Torvalds가 이 레포를 보면 git을 만든 걸 후회할 거예요." },

  // ============================================================
  // 추가 대량 보충 — 1000개 이상 달성을 위한 추가 템플릿
  // ============================================================

  // 브랜치 수와 미머지 다양한 조합 — mild
  { id: "branch", severity: "mild", template: "브랜치 {totalBranches}개에 미머지 {unmergedCount}개. 나쁘지 않아요." },
  { id: "branch", severity: "mild", template: "활성 브랜치가 적절해요. 관리 잘 하시네요." },
  { id: "branch", severity: "mild", template: "브랜치 생명 주기를 잘 관리하시는 것 같아요." },
  { id: "branch", severity: "mild", template: "머지 후 브랜치 삭제를 하시는 좋은 습관!" },
  { id: "branch", severity: "mild", template: "브랜치가 짧게 살다 머지되는 건강한 패턴이에요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치. 이 정도면 관리가 가능한 수준." },
  { id: "branch", severity: "mild", template: "브랜치 수명이 적절해요. 좋은 워크플로우." },
  { id: "branch", severity: "mild", template: "깔끔한 브랜치 관리. 프로의 향기가 나요." },
  { id: "branch", severity: "mild", template: "브랜치가 정돈되어 있어서 보기 좋아요." },
  { id: "branch", severity: "mild", template: "미머지 브랜치가 적어요. 잘 관리하시네요." },
  { id: "branch", severity: "mild", template: "브랜치 전략이 효과적이에요. 유지하세요." },
  { id: "branch", severity: "mild", template: "PR 후 삭제하시는 습관이 좋아요." },
  { id: "branch", severity: "mild", template: "브랜치가 깨끗해요. 이대로 가세요." },
  { id: "branch", severity: "mild", template: "git 워크플로우가 모범적이에요." },
  { id: "branch", severity: "mild", template: "{totalBranches}개 브랜치, 잘 정돈된 레포." },
  { id: "branch", severity: "mild", template: "브랜치 관리 능력이 뛰어나시네요." },
  { id: "branch", severity: "mild", template: "깔끔한 git 사용. 존경합니다." },
  { id: "branch", severity: "mild", template: "브랜치 이름도 괜찮고 수도 적절해요." },
  { id: "branch", severity: "mild", template: "효율적인 브랜치 사용이에요. 칭찬합니다." },
  { id: "branch", severity: "mild", template: "브랜치 워크플로우가 심플하고 좋아요." },

  // 브랜치 패턴 조합 — medium
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개 중 활성이 몇 개인지 파악하세요." },
  { id: "branch", severity: "medium", template: "stale 브랜치를 정기적으로 정리하시면 좋겠어요." },
  { id: "branch", severity: "medium", template: "미머지 브랜치 {unmergedCount}개. 매주 정리하는 습관을 들이세요." },
  { id: "branch", severity: "medium", template: "브랜치 이름에 JIRA 티켓 번호를 넣으시면 추적이 쉬워요." },
  { id: "branch", severity: "medium", template: "이상한 이름의 브랜치 {weirdNameCount}개. 네이밍 룰을 만드세요." },
  { id: "branch", severity: "medium", template: "브랜치 보호 규칙을 설정하시면 사고를 예방할 수 있어요." },
  { id: "branch", severity: "medium", template: "PR 없이 머지하시는 건 리스크가 있어요." },
  { id: "branch", severity: "medium", template: "브랜치 {totalBranches}개인데 태그는 없네요. 릴리즈 관리를 하세요." },
  { id: "branch", severity: "medium", template: "미머지 {unmergedCount}개 중 오래된 건 과감히 삭제하세요." },
  { id: "branch", severity: "medium", template: "브랜치 목록이 좀 지저분해요. 주간 정리를 추천해요." },
  { id: "branch", severity: "medium", template: "활성 브랜치와 비활성 브랜치를 구분하세요." },
  { id: "branch", severity: "medium", template: "브랜치 이름에 슬래시(/)를 쓰시면 계층 구조가 만들어져요." },
  { id: "branch", severity: "medium", template: "이상한 이름 {weirdNameCount}개. 팀 컨벤션을 문서화하세요." },
  { id: "branch", severity: "medium", template: "브랜치 수가 {totalBranches}개면 CI 비용도 신경 쓰세요." },
  { id: "branch", severity: "medium", template: "머지 전략(merge vs rebase)을 통일하셨나요?" },
  { id: "branch", severity: "medium", template: "squash merge를 쓰시면 히스토리가 깔끔해져요." },
  { id: "branch", severity: "medium", template: "브랜치별 권한 설정은 하셨나요?" },
  { id: "branch", severity: "medium", template: "미머지 브랜치 {unmergedCount}개. 리뷰어를 배정하세요." },
  { id: "branch", severity: "medium", template: "브랜치가 main에서 너무 멀어지면 머지가 어려워요." },
  { id: "branch", severity: "medium", template: "정기적인 브랜치 정리가 팀 생산성을 높여요." },

  // 다양한 브랜치 시나리오 — savage
  { id: "branch", severity: "savage", template: "이 레포에서 'git branch'를 치면 터미널이 스크롤 제한을 넘겨요." },
  { id: "branch", severity: "savage", template: "브랜치 이름 '{longestBranchName}'는 소설 제목이에요." },
  { id: "branch", severity: "savage", template: "미머지 {unmergedCount}개! 이 브랜치들의 마지막 커밋 날짜를 확인해보세요. 무서울 거예요." },
  { id: "branch", severity: "savage", template: "이상한 이름 {weirdNameCount}개에 미머지 {unmergedCount}개. 이건 git 쓰레기장이에요." },
  { id: "branch", severity: "savage", template: "브랜치를 만들 때 5초만 더 생각하시면 이런 이름은 안 나와요." },
  { id: "branch", severity: "savage", template: "이 레포의 브랜치 목록을 보면 개발자의 멘탈 상태가 보여요." },
  { id: "branch", severity: "savage", template: "브랜치 관리를 안 하면 나중에 어떤 브랜치가 뭔지 모르게 돼요. 이미 그렇죠?" },
  { id: "branch", severity: "savage", template: "미머지 브랜치에 있는 코드가 필요한 코드일 수 있어요. 확인하셨나요?" },
  { id: "branch", severity: "savage", template: "브랜치가 {totalBranches}개면 cherry-pick이 일상이시겠네요." },
  { id: "branch", severity: "savage", template: "이 레포의 git log --graph --all을 실행하면 모니터가 멈춰요." },
  { id: "branch", severity: "savage", template: "merge conflict 해결이 당신의 주업무 아닌가요?" },
  { id: "branch", severity: "savage", template: "이 브랜치 상태로 코드 리뷰를 하면 리뷰어가 도망가요." },
  { id: "branch", severity: "savage", template: "브랜치 정리를 미루면 미룰수록 상황이 악화돼요." },
  { id: "branch", severity: "savage", template: "git prune을 마지막으로 실행한 게 언제예요?" },
  { id: "branch", severity: "savage", template: "이 레포의 원격 브랜치를 다 가져오면 네트워크가 울어요." },
  { id: "branch", severity: "savage", template: "브랜치 이름에 이모지를 쓰시는 건 아니시죠? ...아, 쓰시는군요." },
  { id: "branch", severity: "savage", template: "이 레포에서 새 브랜치를 만들 때 기존 브랜치 목록 확인하시나요?" },
  { id: "branch", severity: "savage", template: "미머지 브랜치 {unmergedCount}개의 conflict를 한번에 해결하면 3일은 걸릴 거예요." },
  { id: "branch", severity: "savage", template: "브랜치 관리 = 0, 코드 품질 의심. 연관성 100%." },
  { id: "branch", severity: "savage", template: "이 레포의 브랜치 전략을 설명해보세요. '없다'는 답이 아니에요." },

  // 다양한 브랜치 시나리오 — legendary
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치 수는 세계 인구 증가율을 따라가고 있어요." },
  { id: "branch", severity: "legendary", template: "브랜치가 이렇게 많으면 git이 자체적으로 가비지 컬렉션을 거부해요." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치를 전부 시각화하면 은하계 지도가 나와요." },
  { id: "branch", severity: "legendary", template: "미머지 {unmergedCount}개! 이 코드들은 영원히 main을 만나지 못할 운명." },
  { id: "branch", severity: "legendary", template: "브랜치 카오스의 레벨이 MAX! 더 이상 올라갈 곳이 없어요." },
  { id: "branch", severity: "legendary", template: "이 레포의 git graph는 DNA 이중나선보다 복잡해요." },
  { id: "branch", severity: "legendary", template: "브랜치 관리 실패의 교과서! 전 세계 개발자에게 경고해야 해요." },
  { id: "branch", severity: "legendary", template: "이 레포에서 정상적인 브랜치를 찾는 건 사막에서 오아시스 찾기예요." },
  { id: "branch", severity: "legendary", template: "브랜치 {totalBranches}개! git이 이 레포의 ref를 관리하느라 과로사할 지경이에요." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치 상태는 엔트로피의 법칙을 완벽하게 따르고 있어요." },

  // 추가: 머지 전략 관련 — mild
  { id: "branch", severity: "mild", template: "squash merge를 쓰시나 봐요. 깔끔한 히스토리." },
  { id: "branch", severity: "mild", template: "rebase 전략을 쓰시는 것 같네요. 선형 히스토리가 좋아요." },
  { id: "branch", severity: "mild", template: "merge commit이 깔끔하게 있네요. 좋은 패턴." },
  { id: "branch", severity: "mild", template: "fast-forward merge를 선호하시는 것 같아요." },
  { id: "branch", severity: "mild", template: "머지 전략이 일관적이에요. 프로답네요." },

  // 추가: 머지 전략 관련 — medium
  { id: "branch", severity: "medium", template: "머지 전략이 혼재되어 있어요. squash, merge, rebase 중 하나로 통일하세요." },
  { id: "branch", severity: "medium", template: "머지 커밋이 너무 많으면 히스토리가 지저분해져요." },
  { id: "branch", severity: "medium", template: "rebase를 쓰시면서 force push를 자주 하시면 팀원이 고통받아요." },
  { id: "branch", severity: "medium", template: "merge conflict를 resolve하는 커밋이 많으면 브랜치가 너무 오래 살아있는 거예요." },
  { id: "branch", severity: "medium", template: "머지 전략을 팀에서 합의하셨나요?" },

  // 추가: 머지 전략 관련 — savage
  { id: "branch", severity: "savage", template: "force push로 히스토리를 덮어쓰신 적 있으시죠? 팀원의 눈물이 보여요." },
  { id: "branch", severity: "savage", template: "merge conflict가 하루에 3번 이상이면 브랜치 전략에 문제가 있는 거예요." },
  { id: "branch", severity: "savage", template: "rebase 중 conflict 나서 --abort 하신 적 몇 번이에요?" },
  { id: "branch", severity: "savage", template: "git push --force를 공유 브랜치에 하시면 팀원의 커밋이 증발해요." },
  { id: "branch", severity: "savage", template: "머지 전략이 '기도하고 push'이신 건 아닌지." },

  // 추가: 릴리즈/태그 관련 — mild
  { id: "branch", severity: "mild", template: "릴리즈 태그를 잘 사용하시네요. 버전 관리의 기본." },
  { id: "branch", severity: "mild", template: "v1.0.0 형식의 태그가 보여요. 시맨틱 버저닝이시군요." },
  { id: "branch", severity: "mild", template: "태그와 릴리즈가 잘 관리되어 있어요." },

  // 추가: 릴리즈/태그 관련 — medium
  { id: "branch", severity: "medium", template: "태그가 없으면 어떤 버전이 배포됐는지 알 수 없어요." },
  { id: "branch", severity: "medium", template: "릴리즈 관리를 안 하시면 롤백할 때 고생해요." },
  { id: "branch", severity: "medium", template: "태그 없이 {totalBranches}개 브랜치만 있으면 버전 추적이 불가능해요." },

  // 추가: 릴리즈/태그 관련 — savage
  { id: "branch", severity: "savage", template: "태그 0개! 배포 버전을 어떻게 추적하시나요? 텔레파시?" },
  { id: "branch", severity: "savage", template: "릴리즈 관리 없이 운영하시면 장애 때 '어떤 버전이었지?'가 일상이에요." },
  { id: "branch", severity: "savage", template: "태그 없는 레포에서 롤백은 기도 메타예요." },

  // 추가: Git Hook/자동화 관련 — mild
  { id: "branch", severity: "mild", template: "git hooks를 쓰시는 것 같아요. 자동화에 신경 쓰시는 분." },
  { id: "branch", severity: "mild", template: "pre-commit hook이 있으면 코드 품질이 보장돼요." },
  { id: "branch", severity: "mild", template: "자동화된 브랜치 관리가 보여요. 프로답네요." },

  // 추가: Git Hook/자동화 관련 — medium
  { id: "branch", severity: "medium", template: "git hooks 없이 브랜치를 관리하시면 실수가 많아져요." },
  { id: "branch", severity: "medium", template: "pre-commit hook이 없으면 린트 안 돌리고 커밋할 수 있어요." },
  { id: "branch", severity: "medium", template: "자동 브랜치 삭제를 설정하시면 정리가 쉬워요." },

  // 대규모 추가: 다양한 상황별 변형 — mild
  { id: "branch", severity: "mild", template: "브랜치 관리가 안정적이에요. 이대로 가세요." },
  { id: "branch", severity: "mild", template: "워크플로우가 잘 잡혀 있네요." },
  { id: "branch", severity: "mild", template: "브랜치 전략이 프로젝트에 잘 맞아요." },
  { id: "branch", severity: "mild", template: "git을 효율적으로 사용하시는 분." },
  { id: "branch", severity: "mild", template: "브랜치가 깨끗하면 마음도 깨끗해요." },
  { id: "branch", severity: "mild", template: "좋은 브랜치 습관이에요. 유지하세요." },
  { id: "branch", severity: "mild", template: "코드 관리가 체계적이에요." },
  { id: "branch", severity: "mild", template: "이 레포의 브랜치는 건강해요." },
  { id: "branch", severity: "mild", template: "프로답게 브랜치를 관리하시네요." },
  { id: "branch", severity: "mild", template: "브랜치 위생 상태: 우수." },
  { id: "branch", severity: "mild", template: "git 사용법의 교과서 같은 레포." },
  { id: "branch", severity: "mild", template: "브랜치 정리를 잘 하시는 좋은 습관." },
  { id: "branch", severity: "mild", template: "이 레포는 브랜치 관리의 모범 사례." },
  { id: "branch", severity: "mild", template: "워크플로우가 심플하고 효과적이에요." },
  { id: "branch", severity: "mild", template: "브랜치 전략이 명확해요. 좋습니다." },
  { id: "branch", severity: "mild", template: "이 정도면 git 마스터라 불러도 돼요." },
  { id: "branch", severity: "mild", template: "브랜치 이름이 설명적이에요. 좋아요." },
  { id: "branch", severity: "mild", template: "PR 기반 개발을 잘 하시는 분." },
  { id: "branch", severity: "mild", template: "깔끔한 브랜치, 깔끔한 코드." },
  { id: "branch", severity: "mild", template: "이 레포의 git 히스토리가 아름다워요." },
  { id: "branch", severity: "mild", template: "브랜치 수명 관리가 좋아요." },
  { id: "branch", severity: "mild", template: "코드와 브랜치 모두 잘 관리되고 있어요." },
  { id: "branch", severity: "mild", template: "이 레포는 git 사용의 좋은 예시." },
  { id: "branch", severity: "mild", template: "브랜치가 정돈된 레포. 보기 좋아요." },
  { id: "branch", severity: "mild", template: "효율적인 git 워크플로우. 칭찬합니다." },

  // 대규모 추가: 다양한 상황별 변형 — medium
  { id: "branch", severity: "medium", template: "브랜치 정리를 좀 더 자주 하시면 좋겠어요." },
  { id: "branch", severity: "medium", template: "미머지 브랜치가 누적되고 있어요." },
  { id: "branch", severity: "medium", template: "오래된 브랜치가 눈에 띄네요." },
  { id: "branch", severity: "medium", template: "브랜치 네이밍이 일관적이지 않아요." },
  { id: "branch", severity: "medium", template: "git 워크플로우에 약간의 개선이 필요해요." },
  { id: "branch", severity: "medium", template: "브랜치 보호 규칙을 설정하세요." },
  { id: "branch", severity: "medium", template: "PR 리뷰 프로세스를 도입하세요." },
  { id: "branch", severity: "medium", template: "브랜치 수명이 좀 긴 편이에요." },
  { id: "branch", severity: "medium", template: "머지된 브랜치를 자동 삭제하는 설정을 켜세요." },
  { id: "branch", severity: "medium", template: "브랜치 이름에 티켓 번호를 포함하면 추적이 쉬워요." },
  { id: "branch", severity: "medium", template: "이 레포의 브랜치 관리에 C+ 점수를 드려요." },
  { id: "branch", severity: "medium", template: "stale 브랜치를 정리하면 레포가 가벼워져요." },
  { id: "branch", severity: "medium", template: "브랜치 전략을 문서화하세요." },
  { id: "branch", severity: "medium", template: "팀원들과 브랜치 컨벤션을 합의하세요." },
  { id: "branch", severity: "medium", template: "미머지 브랜치 {unmergedCount}개를 이번 스프린트에 정리하세요." },
  { id: "branch", severity: "medium", template: "브랜치 관리는 지속적인 관심이 필요해요." },
  { id: "branch", severity: "medium", template: "이상한 이름의 브랜치를 리네임하세요." },
  { id: "branch", severity: "medium", template: "브랜치가 main과 너무 다르면 머지가 고통이에요." },
  { id: "branch", severity: "medium", template: "주기적인 브랜치 정리를 습관화하세요." },
  { id: "branch", severity: "medium", template: "브랜치 위생 관리에 좀 더 투자하세요." },
  { id: "branch", severity: "medium", template: "불필요한 브랜치는 과감히 삭제하세요." },
  { id: "branch", severity: "medium", template: "브랜치 관리도 코드 품질의 일부예요." },
  { id: "branch", severity: "medium", template: "git 워크플로우를 개선하면 생산성이 올라가요." },
  { id: "branch", severity: "medium", template: "브랜치 이름을 통일하면 팀 협업이 좋아져요." },
  { id: "branch", severity: "medium", template: "미머지 브랜치를 방치하면 점점 머지가 어려워져요." },

  // 대규모 추가: 다양한 상황별 변형 — savage
  { id: "branch", severity: "savage", template: "이 레포의 브랜치 관리는 포기 상태예요." },
  { id: "branch", severity: "savage", template: "브랜치를 정리하지 않으면 결국 새 레포를 파야 해요." },
  { id: "branch", severity: "savage", template: "이 브랜치 상태로는 아무도 협업하고 싶지 않을 거예요." },
  { id: "branch", severity: "savage", template: "git reflog가 당신의 혼돈의 역사를 기록하고 있어요." },
  { id: "branch", severity: "savage", template: "브랜치가 이렇게 엉망이면 코드도 엉망일 거라는 편견이 생겨요." },
  { id: "branch", severity: "savage", template: "이 레포에서 올바른 브랜치를 찾는 건 미로 탈출이에요." },
  { id: "branch", severity: "savage", template: "git gc가 이 레포를 청소하는 데 1시간 걸릴 거예요." },
  { id: "branch", severity: "savage", template: "브랜치 관리를 이렇게 하시면 DevOps 팀이 울어요." },
  { id: "branch", severity: "savage", template: "이 레포의 .git 디렉토리가 코드보다 큰 건 아닌지." },
  { id: "branch", severity: "savage", template: "브랜치가 이렇게 많으면 git clone --depth 1이 필수예요." },
  { id: "branch", severity: "savage", template: "이 레포를 fork하면 브랜치만으로 용량이 어마어마할 거예요." },
  { id: "branch", severity: "savage", template: "merge conflict resolution이 당신의 풀타임 잡이겠네요." },
  { id: "branch", severity: "savage", template: "이 브랜치 목록을 보면 '브랜치 청소 전문가'가 필요한 수준이에요." },
  { id: "branch", severity: "savage", template: "git 히스토리가 이렇게 복잡하면 bisect도 소용없어요." },
  { id: "branch", severity: "savage", template: "브랜치 관리 안 하면 나중에 '어떤 브랜치에서 버그가 시작됐지?'가 미스터리가 돼요." },
  { id: "branch", severity: "savage", template: "이 레포의 git status 결과가 무서울 것 같아요." },
  { id: "branch", severity: "savage", template: "브랜치가 이렇게 산만하면 CI/CD 파이프라인도 혼란스러워요." },
  { id: "branch", severity: "savage", template: "이 레포에서 git fetch --all 하면 터미널이 멈춰요." },
  { id: "branch", severity: "savage", template: "브랜치 정리를 안 하면 어떤 코드가 최신인지 모르게 돼요." },
  { id: "branch", severity: "savage", template: "이 레포의 브랜치 히스토리를 보면 어지러워요." },
  { id: "branch", severity: "savage", template: "미머지 브랜치에 숨겨진 보물(또는 쓰레기)이 있을 거예요." },
  { id: "branch", severity: "savage", template: "이 브랜치 상태는 코드 품질의 적신호예요." },
  { id: "branch", severity: "savage", template: "브랜치 관리가 이래서야 팀 생산성이 나올 리가 없어요." },
  { id: "branch", severity: "savage", template: "이 레포의 git graph는 스파게티보다 꼬여있어요." },
  { id: "branch", severity: "savage", template: "브랜치를 만들기만 하고 책임지지 않으시는 분." },

  // 대규모 추가: 다양한 상황별 변형 — legendary
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치를 전부 머지하면 우주가 폭발할 거예요." },
  { id: "branch", severity: "legendary", template: "브랜치 수가 커밋 수보다 많으면 뭔가 심각하게 잘못된 거예요." },
  { id: "branch", severity: "legendary", template: "이 레포의 git은 자체적인 의식을 가지고 카오스를 만들고 있어요." },
  { id: "branch", severity: "legendary", template: "브랜치 관리의 최하점! 이보다 더 나쁠 수는 없어요. 아마도." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치 상태를 보면 git이 SOS 신호를 보내고 있어요." },
  { id: "branch", severity: "legendary", template: "브랜치 카오스의 궁극체! 이건 컴퓨터 과학이 아니라 카오스 이론이에요." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치를 시각화하면 신경 세포 네트워크보다 복잡해요." },
  { id: "branch", severity: "legendary", template: "브랜치 관리의 최악! 이 레포는 git의 가장 어두운 면을 보여줘요." },
  { id: "branch", severity: "legendary", template: "이 레포에 기여하려면 먼저 브랜치 지도를 그려야 해요." },
  { id: "branch", severity: "legendary", template: "브랜치의 종말론! 이 레포는 git의 아포칼립스를 예고하고 있어요." },

  // 추가: 구체적인 브랜치 이름 패턴 디스 — medium
  { id: "branch", severity: "medium", template: "'wip' 브랜치가 보여요. Work In Progress가 3개월째?" },
  { id: "branch", severity: "medium", template: "'temp' 브랜치... '임시'가 6개월이면 영구예요." },
  { id: "branch", severity: "medium", template: "'backup' 브랜치가 있네요. git이 이미 백업인데 왜 또?" },
  { id: "branch", severity: "medium", template: "'old' 브랜치... 얼마나 오래된 거예요?" },
  { id: "branch", severity: "medium", template: "'new' 브랜치가 1년 전 것이면 더 이상 new가 아니에요." },
  { id: "branch", severity: "medium", template: "'test' 브랜치가 프로덕션에 영향을 주는 건 아니시죠?" },
  { id: "branch", severity: "medium", template: "'dev' 브랜치와 'develop'이 둘 다 있으면 혼란이에요." },
  { id: "branch", severity: "medium", template: "'staging' 브랜치가 main보다 오래됐으면 의미가 없어요." },
  { id: "branch", severity: "medium", template: "'release' 브랜치가 머지 안 되고 방치 중이에요." },
  { id: "branch", severity: "medium", template: "'experimental' 브랜치... 실험 결과는 어떻게 됐나요?" },

  // 추가: 구체적인 브랜치 이름 패턴 디스 — savage
  { id: "branch", severity: "savage", template: "'please-work' 브랜치! 이건 기도가 아니라 코딩을 하셔야..." },
  { id: "branch", severity: "savage", template: "'dont-touch' 브랜치가 있으면 누군가 반드시 건드려요." },
  { id: "branch", severity: "savage", template: "'final-v2-real-final' 브랜치! 이건 final이 아니라 eternal이에요." },
  { id: "branch", severity: "savage", template: "'untitled' 브랜치... 제목 없는 코드, 제목 없는 인생." },
  { id: "branch", severity: "savage", template: "'idk' 브랜치... I Don't Know가 브랜치 이름이면 코드도 IDK겠네요." },
  { id: "branch", severity: "savage", template: "'delete-me' 브랜치... 그럼 삭제하세요! 왜 아직도 있나요?" },
  { id: "branch", severity: "savage", template: "'broken' 브랜치... 이름이 솔직하시네요. 근데 고치세요." },
  { id: "branch", severity: "savage", template: "'save-my-life' 브랜치! 코드가 아니라 당신의 삶이 위험한 건 아닌지." },
  { id: "branch", severity: "savage", template: "'before-everything-broke' 브랜치... 그래서 언제 다 부서진 건가요?" },
  { id: "branch", severity: "savage", template: "'blame-john' 브랜치! 존에게 책임을 전가하는 브랜치. 존은 무죄예요." },

  // 추가: 구체적인 브랜치 이름 패턴 디스 — legendary
  { id: "branch", severity: "legendary", template: "'help-me-god' 브랜치! 신도 이 코드는 못 도와줘요." },
  { id: "branch", severity: "legendary", template: "'im-sorry' 브랜치! 사과 브랜치... 누구에게 사과하시는 건가요?" },
  { id: "branch", severity: "legendary", template: "'this-is-fine' 브랜치! 불타는 강아지 밈이 현실이 된 레포." },
  { id: "branch", severity: "legendary", template: "'sell-the-company' 브랜치! 이 코드를 보면 회사를 팔고 싶어지겠네요." },
  { id: "branch", severity: "legendary", template: "'rewrite-everything' 브랜치! 이 브랜치가 머지되는 날은 오지 않을 거예요." },

  // 추가: 브랜치 수 극단값 — savage
  { id: "branch", severity: "savage", template: "브랜치 {totalBranches}개에 이상한 이름 {weirdNameCount}개. 이건 재난이에요." },
  { id: "branch", severity: "savage", template: "미머지 {unmergedCount}개가 브랜치의 절반이면 이건 심각한 거예요." },
  { id: "branch", severity: "savage", template: "브랜치 수 > 커밋 수면 뭔가 심각하게 잘못된 거예요." },
  { id: "branch", severity: "savage", template: "이 레포에서 활성 브랜치를 찾는 건 바늘 찾기예요." },
  { id: "branch", severity: "savage", template: "브랜치 목록이 이렇게 길면 pagination이 필요해요." },

  // 추가: 브랜치 수 극단값 — legendary
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치 수가 팀원 수의 100배! 1인 100브랜치 시대." },
  { id: "branch", severity: "legendary", template: "브랜치가 커밋보다 많은 전설의 레포! 빈 브랜치의 무덤." },
  { id: "branch", severity: "legendary", template: "이 레포의 브랜치를 전부 출력하면 종이가 부족해요." },
  { id: "branch", severity: "legendary", template: "브랜치 수의 세계 기록을 갱신하셨을 수도 있어요. 기네스에 연락하세요." },
  { id: "branch", severity: "legendary", template: "이 레포의 ref 파일이 코드보다 큰 전설. git이 경악하고 있어요." },

  // 추가: 마지막 보충 (다양한 표현)
  { id: "branch", severity: "mild", template: "브랜치 상태 양호. 이대로 유지하세요!" },
  { id: "branch", severity: "mild", template: "깔끔한 브랜치 전략이에요. A 등급!" },
  { id: "branch", severity: "mild", template: "브랜치 네이밍에서 센스가 느껴져요." },
  { id: "branch", severity: "mild", template: "워크플로우가 효율적이에요." },
  { id: "branch", severity: "mild", template: "브랜치 관리의 모범생이시네요." },
  { id: "branch", severity: "mild", template: "깔끔하게 정리된 브랜치. 감사합니다." },
  { id: "branch", severity: "mild", template: "이 레포는 브랜치 관리가 잘 되어 있어요." },
  { id: "branch", severity: "mild", template: "브랜치 위생 상태: A. 훌륭합니다." },
  { id: "branch", severity: "mild", template: "git을 제대로 활용하시는 분이에요." },
  { id: "branch", severity: "mild", template: "브랜치가 깔끔해서 코드 리뷰가 편하겠어요." },

  { id: "branch", severity: "medium", template: "브랜치 상태가 좀 아쉬워요. 개선 가능해요." },
  { id: "branch", severity: "medium", template: "몇 가지 정리하면 훨씬 좋아질 거예요." },
  { id: "branch", severity: "medium", template: "브랜치 위생 상태: B-. 좀 더 신경 쓰세요." },
  { id: "branch", severity: "medium", template: "오래된 브랜치가 레포를 무겁게 만들어요." },
  { id: "branch", severity: "medium", template: "브랜치 관리에 주의가 필요한 시점이에요." },
  { id: "branch", severity: "medium", template: "git 워크플로우를 한 번 점검하세요." },
  { id: "branch", severity: "medium", template: "미머지 브랜치가 늘어나고 있어요. 주의하세요." },
  { id: "branch", severity: "medium", template: "브랜치 이름을 정리하면 팀원이 행복해져요." },
  { id: "branch", severity: "medium", template: "브랜치 관리 개선이 팀 생산성을 높일 거예요." },
  { id: "branch", severity: "medium", template: "약간의 노력으로 브랜치가 깔끔해질 수 있어요." },

  { id: "branch", severity: "savage", template: "브랜치 위생 상태: F. 대대적인 정리가 필요해요." },
  { id: "branch", severity: "savage", template: "이 브랜치 상태는 팀의 생산성을 갉아먹고 있어요." },
  { id: "branch", severity: "savage", template: "브랜치 관리가 이래서 팀워크가 안 되는 거예요." },
  { id: "branch", severity: "savage", template: "이 레포의 브랜치는 구조를 요청하고 있어요." },
  { id: "branch", severity: "savage", template: "브랜치 정리를 안 하면 결국 모든 것이 무너져요." },

  { id: "branch", severity: "legendary", template: "이 레포의 브랜치 관리는 전설이에요. 앞으로 영원히." },
  { id: "branch", severity: "legendary", template: "브랜치의 무덤에서 유령이 나와요. 머지되지 못한 코드의 원한." },
  { id: "branch", severity: "legendary", template: "이 레포는 브랜치 관리의 역사에서 가장 어두운 장으로 기록될 거예요." },
  { id: "branch", severity: "legendary", template: "브랜치 카오스의 전설! 이 레포는 영원히 기억될 거예요. 나쁜 의미로." },
  { id: "branch", severity: "legendary", template: "git이 만들어진 이래 가장 혼돈스러운 브랜치 상태. 역사적 순간이에요." },
];
